### ISSUE TITLE
create a roadmap (suggestion)

### ISSUE THREAD

**Issue by Alino** [compose/transporter#104]
It would be really nice to have a roadmap on trello like this one https://trello.com/b/oLMMqjVL/telescope-roadmap
Where we could vote for new features and see what is currently in progress

**Comment by nstott** [comment]
a public roadmap is a great idea, 
I'm not sure I'm a trello fan, but we definitely should be more open about the features that we're rolling into each release and the release schedule

for now, I'd really appreciate votes on gh issues, and issues opened about missing features,
and we'll work on formalizing our roadmaps and getting an open process

Thanks!
