### ISSUE TITLE
transporter quits after transporting documents from MongoDB to ES.

### ISSUE THREAD

**Issue by stabenfeldt** [compose/transporter#111]
Hi,

I have created a docker-compose setup to get Elasticsearch, MongoDB and the transporter up and running. https://github.com/soldotno/elastic-mongo/tree/compose-transporter
It does however looks like the transporter quits after moving the existing document from MongoDB to ES.
Is there a way to keep it running?

You should be able to reproduce the error if you do this:
```bash
# Install Docker and Docker-compose first
git clone https://github.com/soldotno/elastic-mongo.git
cd elastic-mongo
git checkout compose-transporter
docker-compose up -d && docker logs -f elasticmongo_transporter_1
```

The output is:

```
Mongo Config {URI:mongodb://mongo1/harvester Namespace:harvester.entries 
Ssl:<nil> Timeout: Debug:true Tail:false Wc:0 FSync:false Bulk:false}
setting start timestamp: 6178783365555027968
transformer: {"data":{"_id":{"$oid":"55bf729f6dd35031aa0ec9ef"},
"content":"It's not summer yet.",
"title":"Breaking news"},"ns":"harvester.entries","op":"insert","ts":1438610108}

```

.. and then the transporter quits.

```bash
$ docker ps -a| ack transpor
6ea1ff8391b5        golang:1.4.2        "/transporter/run.sh   About a minute ago   
Exited (0) 34 seconds ago elasticmongo_transporter_1
```

**Comment by jipperinbham** [comment]
Curious why you would want to keep transporter running after you've copied all documents from source to destination(s)?

**Comment by Alino** [comment]
I think you want to keep the sync running, therefore you need to tail the mongodb oplog.

```javascript
pipeline = Source({name:"mongo, tail:true"})
  .transform({filename: "transformers/passthrough_and_log.js", namespace: "harvester.entries"})
  .save({name:"es", namespace: "harvester.entries"})
```

**Comment by stabenfeldt** [comment]
I need to keep the transporter running, as our main database store is MongoDB, but we use Elasticsearch for search.

@Alino, thanks for the suggestion. I'll give that a go. :+1:

**Comment by stabenfeldt** [comment]
@Alino, adding `tail:true` didn't work. :-(

```
source error, source: hash requires a type field, but no type given
```

**Comment by stabenfeldt** [comment]
@Alino, woop! That worked! :grinning: 
Thanks for helping out.

**Comment by shividhar** [comment]
Could you tell me how you setup the oplog and created the replica set. I did exactly that but I keep getting the following error: `transporter: CRITICAL: Mongodb error (error reading collection read tcp 127.0.0.1:27017: i/o timeout)
CRITICAL: Mongodb error (error reading collection read tcp 127.0.0.1:27017: i/o timeout)`

**Comment by Alino** [comment]
@shividhar I am running mongodb inside docker, to create replica set I run it with these two lines

```shell
docker run --name MongoDB -p 27017:27017 -d mongo --replSet "rs"
docker exec -d MongoDB /bin/bash -c "mongo  --eval \"rs.initiate()\""
```

**Comment by shividhar** [comment]
@Alino Thanks for the reply! Strangely I've found out that transporter only times out when I put my computer to sleep since I'm testing it locally. Otherwise it works without a hitch.
