### ISSUE TITLE
Tail doesn't respect start timestamp

### ISSUE THREAD

**Issue by tombray** [compose/transporter#114]
I'm running a tail with debug on and I see the start timestamp logged as 6179605576914305024, which is correct when bitshifted (1438801544 = 08/05/2015). However, I'm seeing all oplog documents in stdout, starting with the first one from May 2013.

I'm trying to debug this but I don't know Go. Any help would be appreciated!

**Comment by Alino** [comment]
hello,  please why did you close this? did you solve it?
