### ISSUE TITLE
Namespace issue running transporter.

### ISSUE THREAD

**Issue by patsmittty** [compose/transporter#115]
I am getting the following error when running transporter on the following setups:

Cent OS 7 x86_64
transporter version 0.0.4

Ubuntu 14.04 x86_64
transporter version 0.0.4

    $ transporter run --config config.yaml customer/application.js

    $ Mongo Config {URI:mongodb://localhost/dev-gn-api-customer Namespace:dev-gn-api-customer.customers Ssl:<nil> Timeout: Debug:true Tail:false Wc:0 FSync:false Bulk:false}
    $ cannot create transformer adaptor (localmongo/04adf451-888e-43b0-438a-757109c191cf). CRITICAL: can't split transformer namespace (we got a malformed namespace, expected a '.' deliminated string:  || &map[filename:customer/transform.js name:04adf451-888e-43b0-438a-757109c191cf type:transformer])

The error is being thrown in adapter.go (https://github.com/compose/transporter/blob/master/pkg/adaptor/adaptor.go) on line 106. I modified the error to print out the namespace + || + the c variable and that's why the above output is a bit different. For your reference:

    return "", "", fmt.Errorf("we got a malformed namespace, expected a '.' deliminated string: %s || %s", c.GetString("namespace"), c)

It almost seems as if the config file is not being read. If I hard-code my namespace on line 103 in lieu of c.GetString("namespace"), it works as expected. I am running as root user and tried things like changing file permissions, and using full paths with no avail. This exact setup is working on Mac machine's, just seem to be having issues when running on VM Linux setups.

Here are my config file and JavaScript files:

config.yaml

    nodes:
      localmongo:
        type: mongo
        uri: mongodb://localhost/dev-gn-api-customer
        debug: true
      locales:
        type: elasticsearch
        uri: http://localhost:9200/this_gets_ignored
      debug:
        type: file
        uri: stdout://
      transformCustomerFacility:
        type: transformer
        filename: util/transporter/customer-facility/transform.js

customer/application.js

    Source({ name: "localmongo", namespace: "dev-gn-api-customer.customers" }).transform({ filename: "transform.js" }).save({name: "locales",namespace: "golfnow_dev_customers.customer"});

**Comment by jipperinbham** [comment]
you need to add a namespace to the `transform` object in your `application.js` like the following:

```javascript
Source({ name: "localmongo", namespace: "dev-gn-api-customer.customers" }).transform({ filename: "transform.js", namespace: "dev-gn-api./.*/" }).save({name: "locales",namespace: "golfnow_dev_customers.customer"});
```

This change has happened as part of our upcoming release, https://github.com/compose/transporter/blob/master/CHANGELOG.md#v010-unreleased

**Comment by patsmittty** [comment]
Awesome - works for me!

**Comment by letsgolesco** [comment]
This left me confused for a while too - I guess you guys have a more detailed blog post on the way later this week though.

If you aren't working on it already, some documentation would be appreciated! The blog posts become outdated quickly. Also, updating the README would be great (e.g. the example with transformers doesn't give the transformers namespaces).

**Comment by nstott** [comment]
@letsgolesco :+1:

**Comment by chiefy** [comment]
:+1: just ran into this, better docs would be awesome. will try to contribute if I have time!
