### ISSUE TITLE
Transporter:Elasticsearch1.7 unknown parameter [refresh]

### ISSUE THREAD

**Issue by tanalam2411** [compose/transporter#118]
I want to sync MongoDB database with Elasticsearch1.7. For which I created replication set of my db using following command:

```
$ sudo mongod --port 27017 --dbpath /var/lib/mongodb --replSet rs0
```

I have configured transporter 0.1.0 and I run my transporter using following command:

```
$ ./transporter run --config ./test/config.yaml ./test/application.js
```
##### config.yaml

```
api:
   interval: 10s
nodes:
  localmongo:
    type: mongo
    uri: mongodb://localhost/mydb
    tail: true
  es:
    type: elasticsearch
    uri: http://192.168.x.xx:9200/
  timeseries:
    type: influx
    uri: influxdb://root:root@localhost:8086/compose
  debug:
    type: file
    uri: stdout://
  foofile:
    type: file
    uri: file:///tmp/foo
```

So when I try to delete one of the document from mongo it is reflected in mongo collection
(I have replication enabled i.e `oplogs` have been configured as well as I can see the record being deleted in the transporter console) but after this it causes following exception at transporter console and due to this elastic search is not in sync with MongoDB.

```
transporter: CRITICAL: elasticsearch error (2015-08-11 17:36:31.408666556 +0530 IST: 
Error [IllegalArgumentException[Action/metadata line [1] 
contains an unknown parameter [refresh]]] Status [500] [500])
```

**Comment by codepope** [comment]
The issue appears to be with the Elastigo library. An issue here - https://github.com/mattbaird/elastigo/issues/215 - seems to note the problem as it affects Elastigo.
https://github.com/elastic/elasticsearch/issues/11690 - covers issues around it affecting the wider Elastic world.

**Comment by jipperinbham** [comment]
@tanalam2411 we've updated the elastigo library with the 0.1.1 release, can you check and see if you're still having the issue?

**Comment by letsgolesco** [comment]
@jipperinbham I just ran into this issue using the v0.1.1 release - downloaded the .tar, running it on ubuntu.

**Comment by jipperinbham** [comment]
closing this in favor of https://github.com/compose/transporter/issues/209
