### ISSUE TITLE
Config environment variable regexp should include underscores

### ISSUE THREAD

**Issue by letsgolesco** [compose/transporter#119]
Hey guys,

PR #100 addressed issue #88 and added environment variables (thanks for that btw!) but it didn't seem to work for me for some reason - I think I've figured out why.

The regexp used to detect environment variables in the config only covers letters and digits, but environment variables commonly contain underscores. For example, I'm using docker links to connect my transporter to databases, and environment variables for IP addresses/ports are generated as such: https://docs.docker.com/userguide/dockerlinks/#environment-variables

The regexp in question is: https://github.com/compose/transporter/blob/master/cmd/transporter/config.go#L67

A fix I made locally was to change the regex from `\$\{([a-zA-Z0-9]+)\}` to `\$\{([a-zA-Z0-9_]+)\}` (simply added an underscore in the capturing group). This fixes the issue for me, I'll make a PR with the change to keep you guys freed up.

**Comment by jipperinbham** [comment]
closed via #120
