### ISSUE TITLE
Constant disconnects

### ISSUE THREAD

**Issue by ambasta** [compose/transporter#121]
Hi,

We've set up transporter against one of our mongo databases. However, after syncing a good number of documents, transporter seems to disconnect from mongo and is unable to reconnect thereafter throwing:

"got err reading collection. reissuing query read tcp {host}:{port} i/o timeout"

We've ensured that the host running transporter is indeed able to connect to the mongo server in question while the error is being thrown. How do I resolve this issue?

**Comment by jipperinbham** [comment]
Hi @ambasta, 

I'm assuming you're getting the error doing a straight copy? Can you give us an estimate of how much data it is you have? 

Does transporter fail consistently after a certain amount of time or does it vary?

The i/o timeout typically occurs when the server doesn't respond to a query within the default socket timeout (which I believe is 30s).

**Comment by ambasta** [comment]
Hi,

We have configured transporter to tail oplog. However, the error occurs during initial sync of the collection.

The collection has roughly 10m records and the failure occurs at varied times.

**Comment by WesleyDavid** [comment]
@ambasta That sounds more like a failure on the part of the source MongoDB instance. Have you checked the MongoDB logs for what's happening around the time that the Transporter fails? I'd suggest tailing the MongoDB logs of the instance that you're pointing Transporter at, then kicking off a Transporter.

Is the source a replica set or a single host?

**Comment by ambasta** [comment]
I have kicked off another session of transporter with the release version 1.0.0, will monitor mongo logs to verify any issues with the host.

The source is a replica set and I've specified transporter to connect to a hidden secondary.

**Comment by ambasta** [comment]
Hi,

So I've been running transporter on a server on its own and I've been unable to replicate the issue. Closing this issue for now
