### ISSUE TITLE
Installation fails at godep go build -a ./cmd/... with pkg/adaptor/elasticsearch.go:123: not enough arguments in call to e.indexer.Index

### ISSUE THREAD

**Issue by ambasta** [compose/transporter#122]
It seems that Bulk Indexer in ESGo has been updated to take a parent parameter.

Changing pkg/adaptor/elasticsearch.go:123 from
```
	err = e.indexer.Index(e.index, _type, id, "", nil, msg.Data, false)
```
to
```
	err = e.indexer.Index(e.index, _type, id, "", "", nil, msg.Data, false)
```
resolves the issue.

**Comment by lvidarte** [comment]
Same error here...

**Comment by jipperinbham** [comment]
You'll probably want to run
```
godep restore
```
before running
```
godep go build
```
this will ensure that the dependencies used to build the project are the same as when the elasticsearch adaptor was last worked on.

**Comment by stabenfeldt** [comment]
Hi,

I get the same error. @jipperinbham, your suggestion did not work. I'm testing with the latest master branch. 

```
/go/src/github.com/compose/transporter# godep restore
/go/src/github.com/compose/transporter# godep go build
can't load package: package github.com/compose/transporter: no buildable Go source files in /go/src/github.com/compose/transporter
godep: go exit status 1
```

You can recreate the issue if you use Docker:
```
docker run -i -t golang:1.5 /bin/bash
cd $GOPATH; mkdir pkg
mkdir -p src/github.com/compose; cd src/github.com/compose
git clone https://github.com/compose/transporter; cd transporter

go get -a ./cmd/...
### Fails:
# github.com/compose/transporter/pkg/adaptor
# pkg/adaptor/elasticsearch.go:123: not enough arguments in call to e.indexer.Index

# Install as described in the README
```
Any other suggestions?

**Comment by nstott** [comment]
Hey,
in your first example you need to do a `godep restore`, and then a `godep build ./cmd/...`
in your second example the build command is right, but you need to use the `godep restore` instead of the `go get`

**Comment by stabenfeldt** [comment]
```
godep build ./cmd/...
godep: unknown command "build"
Run 'godep help' for usage.
```

**Comment by nstott** [comment]
sorry my bad, `godep go build ./cmd/...`

**Comment by stabenfeldt** [comment]
Yeah, that worked! :-)
But where is the **transporter** binary put?

**Comment by nstott** [comment]
if you `godep go install ./cmd/...` it gets put into your $gopath/bin, when you just go build it like that it will drop the binary in cmd/transporter

**Comment by stabenfeldt** [comment]
Ok, thanks! I've never used godep, as you understand. :-)
BTW: The binary was saved in the root source directory, not in cmd.

**Comment by lvidarte** [comment]
Thanks @jipperinbham, @nstott ! now is working.

**Comment by stabenfeldt** [comment]
Yeah, works for me too. :+1:

**Comment by jipperinbham** [comment]
fixed via https://github.com/compose/transporter/commit/5f4b52f2376a4f0a2f31bcf4edf0c0cff6506db1

**Comment by ShockiTV** [comment]
How exactly this manual workaround to every time patch local version help us instead of adding that 1 `, ""` into elasticsearch.go on line 123? Can you please commit that instead of readme?
this is the needed current form:
err = e.indexer.Index(e.index, _type, id, "", "", nil, msg.Data, false)

**Comment by jipperinbham** [comment]
@ShockiTV imo this specific issue came up because of the missing `godep restore` step in the README. Had it been there, the compile error would not have been raised because the build step would have used the vendored dependency.

I do agree the elasticsearch adaptor needs to be updated with the latest changes from the elastigo library. I've created https://github.com/compose/transporter/issues/124 to address the specific issue of the elastigo library changes.
