### ISSUE TITLE
Transporter slowdown

### ISSUE THREAD

**Issue by ambasta** [compose/transporter#123]
Hi,

We've been able to configure transporter and get it to sync to sync. Our DB is roughly 10m records, and while the first 7m synced in under a day, 7m-8.5m took a day and currently 8.5m-9.5m has already taken over a day and half ( theres still another 500k to go)

How do I debug/resolve this issue?

**Comment by ambasta** [comment]
Hi, It has still been still at 9.7m and is progressing slower than ever.

**Comment by nstott** [comment]
This is interesting..
what I would look at the source and the sink database and see how performant they are.
perhaps the transporter is dealing with sinks that are heavily locked.
eg. if it's mongo, then mongostat might be a good tool to use to examine the db

if you think it's transporter, then perhaps it's running out of memory and swaping?  what is the health of the system running transporter like?

**Comment by ambasta** [comment]
The system running transporter has 2% cpu, 30% memory utilization. The database is not locked mostly.

I have been able to reproduce the issue with transporter over a span of an hour, where the transfer rate (documents/minute) keeps dropping every minute.

**Comment by nstott** [comment]
do you get the same slow down if you dump to something that doesn't lock, like a file, or like stdout?
if that doesn't experience a slowdown, then i would look into the sink

**Comment by ambasta** [comment]
Will try to reproduce by dumping to a file tonight. Also to be noted, is that the errors wrt elasticsearch [transporter: CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [33])] also increase in frequency, with time.

**Comment by ambasta** [comment]
It was able to dump to /dev/stdout just fine,

**Comment by nstott** [comment]
This seems to be an issue with the destination database.  i would look at the health of this, see if it's resource constrained, and possibly allocate more ram / heap to this.

**Comment by ambasta** [comment]
Resolved this by fixing Bulk Insertion Error. Failed item count error due to mapping mismatches
