### ISSUE TITLE
MongoLab Oplog Tail Issue

### ISSUE THREAD

**Issue by shividhar** [compose/transporter#126]
Hi all. I'm using MongoLab as my data store but I can't enabling tailing on my transporter instance. The data gets transferred once before spitting out this error: `transporter: CRITICAL: Mongodb error (error reading collection not authorized for query on local.oplog.rs)`. There was a similar issue #69 but I didn't find it helpful.

I would appreciate any help.

**Comment by nstott** [comment]
Hi,
the mongo user needs to have access to the local database
getting admin on your mongo database is the easiest way to ensure this.
they seem to offer it on some plans, see: http://docs.mongolab.com/connecting/ and search for 'admin'
if you can't get admin, then it's best to create a user that has full access to the local database

hth

**Comment by shividhar** [comment]
Thanks a lot @nstott. Yeah I was using the Shared Cluster which wouldn't work.

**Comment by chiefy** [comment]
:+1: thanks, just ran into this using MongoLab shared.
