### ISSUE TITLE
How does one use the sessions feature to resume transporter to resume tailing data from mongodb after crash

### ISSUE THREAD

**Issue by ambasta** [compose/transporter#130]
Hi, it seems #116 has been merged into master which implements the sessions feature to store the progress of sync.

If my transporter is closed during a sync, how can I use this feature to resume it?

**Comment by SherClockHolmes** [comment]
:+1:

**Comment by jipperinbham** [comment]
right now none of the adaptors have implemented the functionality to make use of the session store, we hope to have that work going soon.

**Comment by patmanh** [comment]
@jipperinbham any updates here? anything we can do to help contribute?

**Comment by ebaizel** [comment]
+1 happy to contribute as well.

**Comment by Apoorva333** [comment]
Any updates here ?

**Comment by jipperinbham** [comment]
the work needed to make this possible is being tracked in https://github.com/compose/transporter/issues/33 but the current focus is still getting adaptor stability in place.
