### ISSUE TITLE
installation fails - too many arguments in elasticsearch.go adapter

### ISSUE THREAD

**Issue by Alino** [compose/transporter#135]
when I am trying to install transporter, it fails on this step:

```
go get -a ./cmd/...
```

giving these errors:

```
pkg/adaptor/elasticsearch.go:120: too many arguments in call to e.indexer.Delete
pkg/adaptor/elasticsearch.go:123: too many arguments in call to e.indexer.Index
```

I tried to fix it in this PR https://github.com/compose/transporter/pull/134

the tests are failing but at least I am able to install it now.

**Comment by letsgolesco** [comment]
Is anybody looking at this? I'm getting the same error when attempting to install the new version. There's a clear mismatch between the function arguments expected and arguments given.

Elastigo `Bulkindexer.Delete`
definition: https://github.com/mattbaird/elastigo/blob/53bd637ad02af3043244da16c1b9f13633e8e912/lib/corebulk.go#L309
usage: https://github.com/compose/transporter/blob/master/pkg/adaptor/elasticsearch.go#L120

Elastigo `Bulkindexer.Index`
definition: https://github.com/mattbaird/elastigo/blob/53bd637ad02af3043244da16c1b9f13633e8e912/lib/corebulk.go#L289
usage: https://github.com/compose/transporter/blob/master/pkg/adaptor/elasticsearch.go#L123

Each are being given an extra argument - it looks as if the final argument (`false`) is unnecessary in both cases.

**Comment by Alino** [comment]
It's been almost a month since somebody from compose team answered or took any action regarding this project. So I guess they are busy right now. However I am using transporter with that fix I made and it works.

**Comment by codepope** [comment]
The issue comes if you are following the head of the elastigo project. The change was made 19 days ago and appears to be part of redesigning how the BulkIndexer works. 

https://github.com/mattbaird/elastigo/commit/c698cdaa601e80e722feffba2a0b5284624160ef

You can of course build the project with any version of Elastigo pre that commit.

**Comment by letsgolesco** [comment]
Thanks for the heads up @codepope - how would I go about changing the commit from which elastigo is built? I've just been using `go get -a ./cmd/...` and `go build -a ./cmd/...` to build everything.

Seems as if the dependency versions should be shrink wrapped to prevent future issues like this from occurring.

**Comment by Alino** [comment]
I am installing transporter with docker, this is my dockerfile where I specify different github branch (forked one)
```
FROM golang:1.4.2

RUN mkdir -p /go/src/github.com/compose
RUN cd /go/src/github.com/compose && git clone https://github.com/Alino/transporter.git && \
    cd transporter && git checkout patch-1
RUN cd /go/src/github.com/compose/transporter && go get -a ./cmd/...
RUN cd /go/src/github.com/compose/transporter && go build -a ./cmd/...

ENV GOPATH /go
WORKDIR /go/src/github.com/compose/transporter
```

**Comment by jipperinbham** [comment]
we also provide steps in the README, https://github.com/compose/transporter#build

we added Godep as a result of constant changes with elastigo as well as the gorethink driver

**Comment by letsgolesco** [comment]
@jipperinbham thanks for the heads up, built with godep and it worked fine. You guys have 2 different build processes in the README which was confusing, I was under the impression that you had to do both (not very familiar with golang).

**Comment by Alino** [comment]
I had some issues in the past, using godep, that's why my dockerfile is not using it. I will try it next time if I will have to rebuild the docker image again.

**Comment by phber** [comment]
Could you clarify if there is any fix to this issue? I have been doing a fresh install on Windows following the steps in the READMEWINDOWS. I am also getting the following errors:

> pkg/adaptor/elasticsearch.go:120: too many arguments in call to e.indexer.Delete
> pkg/adaptor/elasticsearch.go:123: too many arguments in call to e.indexer.Index

I tried using godep go install without solving the problem...

**Comment by hanjoyo** [comment]
@Alino Sir, maybe you missed this step [https://github.com/compose/transporter#build](installing godep)

I managed to generate the transporter.exe file **after installing godep** and repeat these process:
go get -a ./cmd/transporter
go build -a ./cmd/transporter

**Comment by hanjoyo** [comment]
revise the link:
[installing godep](https://github.com/compose/transporter#build)

**Comment by jipperinbham** [comment]
closing this in favor of https://github.com/compose/transporter/issues/209
