### ISSUE TITLE
MongoDB to MongoDB + tail

### ISSUE THREAD

**Issue by fjg** [compose/transporter#137]
Hi,
first thanks for this tool!

I am trying to synchronize two MongoDB databases. One is a live DB, the other one is used for analytics/datamining purpose. We are using Mongo 2.4.
Everything is fine without the tail option. Transporter syncs our second database every time we launch it (no resume until now afaik).

But adding **tail: true** makes it failed with this error:

```
transporter: CRITICAL: Mongodb error (error reading collection tailable cursor requested on non capped collection)
CRITICAL: Mongodb error (error reading collection tailable cursor requested on non capped collection)
```

None of our collections are capped.

Also, what's the best to keep our DB sync:
- run a cron job without tail option
- makes the tail working and daemoize transporter

How are handle connection issue in both scenarii?

**Comment by ambasta** [comment]
Tail needs access to local.oplog.rs which is a capped collection ( and exists only for replica set setups afaik)

Verify that you have access to oplog rs on the user being used to connect transporter

**Comment by fjg** [comment]
It does, it was failing before without syncing anything.
Now it can sync without "tail" but fails once we enable this option.

**Comment by ambasta** [comment]
Is your source MongoDB running as a replicaset? Can you verify if you can create a tailable cursor on your Oplog via:
```
use local
db.oplog.rs.find().addOption(  DBQuery.Option.tailable ).addOption(DBQuery.Option.awaitData)
```

**Comment by fjg** [comment]
````
> use local
switched to db local
> db.oplog.rs.find().addOption(  DBQuery.Option.tailable ).addOption(DBQuery.Option.awaitData)
error: {
        "$err" : "tailable cursor requested on non capped collection",
        "code" : 13051
}
````

**Comment by ambasta** [comment]
That just goes on to show that either you're not running mongoDb as a replicaset or you don't have access to oplog.rs

Both those conditions need to be true for you to enable tail on transporter

**Comment by Alino** [comment]
@fjg why don't you use mongo's native feature of hidden replica set members? https://docs.mongodb.org/v2.4/core/replica-set-hidden-member/

**Comment by jipperinbham** [comment]
closing this as it appears the issue was with the type of mongodb being run either not being a replica set or the user didn't have permissions to read from `local.oplog`
