### ISSUE TITLE
Enhancement: Output different namespace

### ISSUE THREAD

**Issue by cristobal** [compose/transporter#140]
It would be nice to have an different namespace for the output i.e:

```
 Source({name: "mongo", namespace: "foo.bar"})
  .transform({filename: "transformers/process.js", namespace: "foo.bar"})
  ...
  .save({name: "es", namespace: "foo.bar"});
```

Always requires that both input and destination is the same namespace.
And ends up in this case from the _mongo_ collection `foo.bar` into the _elasticsearch_ index `foo/bar`.

But in some cases one would like to export to a different namespace than the default namespace used to math input/output such a feature could be e.g:

```
 Source({name: "mongo", namespace: "foo.bar"})
  .transform({filename: "transformers/process.js", namespace: "foo.bar"})
  ...
  .save({name: "es", namespace: "foo.bar", outputNamespace: "collections.baz"});
```

This is just a suggestion.
Where the input from `foo.bar` int the _mongo_ collection ends into the `collections/baz`  -> index/mapping in _elasticsearch_ instead of `foo/bar`.

As far as i can this is possible with _[Embulk](http://www.embulk.org/docs/)_, this would be a killer feature for _transporter_ to have.

**Comment by codepope** [comment]
You can change the namespace within a transformer and set it to your desired target namespace. You can then set the sink to save for that namespace. This allows the transformer script to target different sinks using different namespaces.

See "changing namespaces" in https://www.compose.io/articles/transporters-namespace-aware-data-transfer/

**Comment by cristobal** [comment]
Ok did not know that this site misses a wiki section for more complex examples that the articles thanks for the input here. 

But still this raises question as why do i need a transformer for that?
Is it not easier to add this as part of the output sink as part of the `options` in the `.save({...})` operation.

**Comment by Alino** [comment]
I was doing something similar here https://github.com/compose/transporter/issues/133

**Comment by cristobal** [comment]
@Alino thanks yes i got it working, but still think this should be an enhancement as part of the options in the output sink.

**Comment by jipperinbham** [comment]
@cristobal sorry for the lack of documentation and DSL changes.

the original purpose for the `namespace` was for defining the database/index + table/collection but when we wanted the ability to perform easy filtering, we chose to repurpose the `namespace` attribute and turned it into a regexp where the pipeline would only route messages if the document namespace matched the namespace on the node.
