### ISSUE TITLE
 CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [11])

### ISSUE THREAD

**Issue by adeshpandey** [compose/transporter#141]
After writing nearly 1639648 records transporter says this error and elastic search logs have nothing to show.

**Comment by Alino** [comment]
this error should be more verbose I think, I never understood what this error means what is the root cause.

**Comment by adeshpandey** [comment]
I do not have any other log for this

**Comment by jipperinbham** [comment]
closing this in favor of https://github.com/compose/transporter/issues/209
