### ISSUE TITLE
Maintaining key order on stream

### ISSUE THREAD

**Issue by e0d** [compose/transporter#143]
We, unfortunately, have a code dependency on the order of a composite key field.  The field looks like:

```
"_id" : { "tag" : "tag", "org" : "foo", "course" : "123x", "category" : "vertical", "name" : "8cf046ac8a6344d0a0949bfed6c1b2a0", "revision" : null }
```

Fixing this in our code is complex.  Any sense of how tractable it would be to alter transporter to maintain order

**Comment by jipperinbham** [comment]
transporter currently relies on https://github.com/compose/mejson for serializing mongodb documents and it currently doesn't handle ordering of they keys
