### ISSUE TITLE
Cannot create mongo adaptor (localmongo) no reachable servers

### ISSUE THREAD

**Issue by zonagit** [compose/transporter#145]
when I run 

transporter run --config ./test/config.yaml ./test/application.js

I get

js sessions config -> {  }
Mongo Config {URI:mongodb://localhost/somedb Namespace:somedb.somecol Ssl:<nil> Timeout: Debug:true Tail:false Wc:0 FSync:false Bulk:false}
cannot create mongo adaptor (localmongo). no reachable servers

I can reach mongo from the shell though. Any way of tracing what the issue might be?

**Comment by Alino** [comment]
why close? did you solve it?

**Comment by zonagit** [comment]
No but I found a workaround.
All my installation was on a Windows 7 machine.
My workaround was to install go and transporter on a linux vm
and leave the source and destination in windows and it worked that way.

**Comment by txappmkr** [comment]
Facing the same issue, any inputs to solve this would be great

**Comment by mikpan** [comment]
It is most likely the driver is having hard time to resolve "localhost". Try using "mongodb://127.0.0.1/somedb" instead.

To debug connection you can find helpful the following technique: http://stackoverflow.com/questions/20976030/golang-mgo-panic-no-reachable-servers

**Comment by ebaizel** [comment]
thanks @mikpan that did the trick for me

**Comment by jipperinbham** [comment]
issue cleanup
