### ISSUE TITLE
Set strings to not be analyzed by Elasticsearch index

### ISSUE THREAD

**Issue by luigibertolucci** [compose/transporter#146]
I've been looking around and only found a transform for Integer using Number from the Underscore.js but I can't find anything related to a String not being analyzed when transporting the data into Elasticsearch.

My issue is that I have data in MongoDB and wanted to pass it to Elasticsearch but I have a few fields that contain "-" and/or " " and when using the Transporter, they always end up of type String and "analyzed" and it breaks my Elasticsearch queries.

I tried to create the index first, with no data, into Elasticsearch and I see the mappings but they don't get assigned to any fields.

I would also need to create a Geo_Location field in Elasticsearch and I know it's possible to build such a field in a transformer but how do you pass the type for such a field to Elasticsearch.

Is there a way to specify with a transformer, what type of fields and if they should be analyzed or not?
I'm guessing it can be done, I just don't know how...

**Comment by jipperinbham** [comment]
closing this in favor of https://github.com/compose/transporter/issues/209
