### ISSUE TITLE
wrong parameters for ./github.com/mattbaird/elastigo/lib/corebulk.go index and delete function

### ISSUE THREAD

**Issue by Bubbachuck** [compose/transporter#147]
func (b *BulkIndexer) Delete(index, _type, id string) 

In compose/transporter/pkg/adaptor/elasticsearch.go
 e.indexer.Delete(e.index, _type, id, false)

**Comment by jipperinbham** [comment]
closing this in favor of https://github.com/compose/transporter/issues/209
