### ISSUE TITLE
Tailing all collections

### ISSUE THREAD

**Issue by refaelos** [compose/transporter#150]
Hey,

I'm just making sure i'm doing it right...

I have 2 Mongo instances and i'm trying to stream data from one to the other. I want to stream all collections actively with `tail`. What I did is I used a namespace `database./.*/` and it looks like it's doing the job (with some delay). 

The documentation is saying I need to specify a specific collection in the namespace but using a wildcard works. Am I missing something or is it the expected behavior?

**Comment by ernoaapa** [comment]
:+1:

**Comment by jipperinbham** [comment]
@refaelos you are using the namespace properly to sync all collections. In earlier versions, transporter could only do individual collections at a time. The namespace takes a regex that gets evaluated throughout the pipeline. This allows for lots of flexibility in what collections go where.
