### ISSUE TITLE
Exact namespace matches like regex

### ISSUE THREAD

**Issue by ernoaapa** [compose/transporter#153]
Hi,
Just found out that if I use `my_db.User` as namespace as source, and I have `FooUser` and/or `UserFoo` collection in my database, it will copy all collections `*User*` collections.
## Example

```
# Create test data to MongoDB
> db.User.insert({test:"user collection"})
> db.FooUser.insert({test:"foo user collection"})
> db.UserFoo.insert({test:"user foo collection"})
```

```
# Run 
Source({name:"source_mongo", namespace: 'my_source_database.User'})
  .save({name:"target_mongo", namespace: 'my_target_database./.*/'});
```

`my_target_database` contains now collections `User`, `FooUser` and `UserFoo`.

Transporter version: 0.1.1
Host: OS X El Capitan 10.11.1

**Comment by codepope** [comment]
Anchor the regexp if you want an exact match using `/^User$/`... It is a regexp and as such is unbounded for flexibility.

**Comment by ernoaapa** [comment]
Ok using `Source({name:"source_mongo", namespace: 'my_source_database./^User$/'})` helped.

This is quite confusing for the user because from documentation I understand that `'my_source_database.User` would be exact match (because no //).

Anyway now I get forward, thanks!

**Comment by dortort** [comment]
This should be, at least, be documented.

@codepope Could you please expand on the _"flexibility"_ that is required/ desired in this case?

**Comment by jipperinbham** [comment]
@dortort the _flexibility_ @codepope is referring to is because the underlying implementation is using the [regexp package](https://golang.org/pkg/regexp/) which provides numerous capabilities for filtering collections/tables. 

we hope to have some usability improvements soon that should help clear up cases like this.
