### ISSUE TITLE
Incompatible with AWS ES service (needs signed requests)

### ISSUE THREAD

**Issue by chiefy** [compose/transporter#159]
I am trying to use transporter inside an AWS Lambda function, but in order to access my AWS ES cluster, I need the https requests to be signed by a specific IAM role. Unfortunately this seems to be the only way of using Lambda with AWS ES securely. I've tested transporter inside Lambda to AWS ES w/ no security and it seems to work fine, FWIW.

**Comment by ukch** [comment]
I have created PR #203 to deal with this issue. Please check out my branch if you need to use Transporter with signed requests.

**Comment by jipperinbham** [comment]
fixed in [v0.1.2](https://github.com/compose/transporter/releases/tag/v0.1.2)
