### ISSUE TITLE
adaptor for tokumx 

### ISSUE THREAD

**Issue by perannum** [compose/transporter#162]
Hello,

I have been trying to use transporter with tokumx 1.5.0 to import data in elasticsearch. I have had success importing the data from tokumx to elasticsearch but have issues in syncing the data apparently due to change in format of oplog.rs file of tokumx. I am interested to know if the format is only reason tailing is not happening? I have tried to change the adaptor's file but my changes are not reflected. Can I have some insights into how to enhance/update adaptor's code? Thanks

**Comment by jipperinbham** [comment]
I'm not familiar with all the differences between the tokumx oplog and the standard mongodb one but if it's different enough that things do not work out of the box, I don't expect transporter to support it.
