### ISSUE TITLE
load mongo object while transporting to ES

### ISSUE THREAD

**Issue by mzahidriaz** [compose/transporter#163]
```
{
  objectId: 12312312312312312,
  name: "Some name",
  anotherDocId: 12312312323123123123
}
```

While transporting this to ES I want to load `anotherDocId` from mongo and add as a json object before transporting to ES.

Expected Output

```
{
  objectId: 12312312312312312,
  name: "Some name",
  anotherDocId: {
    name: "Another Document Name"
  }
}

```

**Comment by jipperinbham** [comment]
this would be implemented as part of https://github.com/compose/transporter/issues/39
