### ISSUE TITLE
Error "got err reading collection. reissuing query read tcp" is never recovered from

### ISSUE THREAD

**Issue by dblock** [compose/transporter#164]
I had a job stuck on this for a few hours in a Compose hosted environment, https://app.compose.io/artsy/deployments/gravity-staging-mongodb-deployment/mongodb/databases/gravity-staging/imports. It never resumed.

![screen shot 2016-01-20 at 1 15 44 pm](https://cloud.githubusercontent.com/assets/542335/12458459/02aca7f8-bf78-11e5-802d-92e838c92a53.png)

I had another `mongodump` running from the same database in parallel so I am fairly sure that's what caused this. However I think there might be a bug here where this error cannot be recovered from.

https://github.com/compose/transporter/issues/121 seems to be related

**Comment by ebaizel** [comment]
i ran into the same today.  it ran for 3 hours before that message appeared and then it never recovered.  

* the source is a `mongo 2.4` database and the destination is a `mongo 3.2`.  
* the source is reading from a `secondary` replica node
* did not have a `mongodump` running separately

**Comment by jibsheet** [comment]
I see this pretty routinely reading from a 2.6 secondary, dumping into a 3.0.
Only occurs if the 2.6 is under load.
Would be nice if it retried, which it never seems to do, it gets stuck running
`got err reading collection. reissuing query read tcp .... i/o timeout`

**Comment by jipperinbham** [comment]
can you try using the `experimental` branch? we've added the following:

```go
m.mongoSession.SetSocketTimeout(time.Hour)
```

and think it has solved the issue as we no longer see the error when running it internally.

**Comment by ebaizel** [comment]
awesome to hear you guys might have solved.  unfortunately the infrastructure we had set up to run transporter has been taken down, so i won't be able to test it.

we did end up getting it to work though.  if i recall we ended up setting multiple transporters, with large collections getting their own and smaller collections being grouped into one transporter.  that seemed to have helped a lot.

**Comment by jipperinbham** [comment]
cool, closing this out for now but we can always reopen if it still persists.

**Comment by M-Zuber** [comment]
I am still seeing this issue.
mongo -> aws es
approx 10.5k documents.

I ran the linux binary (last stable release) on bash on ubuntu on windows 10 if that might make a difference

**Comment by M-Zuber** [comment]
I tried running it with the experimental release, and it is throwing that error after only 400 documents

**Comment by jipperinbham** [comment]
@M-Zuber thanks for testing! looking at the code in the last experimental release, it did not contain the fix. We hope to get a new release out for experimental very soon so if you can build from source, that'd be a big help as I've not been able to reproduce from my latest build.

**Comment by M-Zuber** [comment]
Unfortunately I am unable to build from source right now,  but I have [subscribed to releases](https://libraries.io/go/github.com%2Fcompose%2Ftransporter) and will try and test it again with the new experimental release whenever that drops
