### ISSUE TITLE
Documents Updated

### ISSUE THREAD

**Issue by Kjta** [compose/transporter#167]
Hi, I'm a new and happy user of Compose and Transporter. But I see that if I update an doc on mongo, I have an new doc in ES. There is some way to update the same doc (with the same mongoID) also on ES?

**Comment by codepope** [comment]
Is this ES 2.0 or later?

**Comment by Kjta** [comment]
I use ES 2.1.0

**Comment by ndouba** [comment]
Please see pull request https://github.com/compose/transporter/pull/168

**Comment by jipperinbham** [comment]
fixed in the latest release [v0.1.2](https://github.com/compose/transporter/releases/tag/v0.1.2)
