### ISSUE TITLE
side-effect(s) of conforming matchType in ElasticSearch adaptor

### ISSUE THREAD

**Issue by siddharthlatest** [compose/transporter#170]
I am using the ElasticSearch adaptor as a sink to read data from JSON files. A side effect of how the adaptor is currently implemented (reading data from MongoDB) is that it conforms the user provided namespace (either in configuration or in a transformation file) with the file name.

The following configuration
![](https://i.imgur.com/9UWC2Yh.png)

with transformation file as follows
![](https://i.imgur.com/HcnOrql.png)

will not work. The only acceptable namespace here is `./sourcetransformfile.json`, a side-effect of the normal use-case of reading from MongoDB where type conformation is required b/w a Mongo and ElasticSearch source / sink.

The above scenario is not just bad from an aesthetic standpoint, but also it doesn't work - since starting v2.0, ES doesn't accept typenames starting with a period (.).

---

I am reading between the lines here about the original ES adaptor's design goals. How important is conforming a type to a similarly named MongoDB collection? The current implementation prevents using ES as a sink for a file based source.

**Comment by codepope** [comment]
Check out the section on https://www.compose.io/articles/transporters-namespace-aware-data-transfer/ on changing namespaces in transit.

This as a transform with a namespace of "file.\.sourcetransformfile\.json" should work...

module.exports = function(doc) {  
  doc.ns="moviedb.user_defined_namespace"
  return doc;
}

**Comment by siddharthlatest** [comment]
@codepope that works. Although I wonder, wouldn't it be more intuitive to support sink's namespace when the source is a file (i.e. no inherent matching constraints)?

**Comment by codepope** [comment]
That would mean back propogating the sinks namespace through the pipeline based on source. Thats potentially scary and even more unintuitive.

**Comment by jipperinbham** [comment]
closing since there is currently a work around for sinking from a file and future improvements to namespacing is planned.
