### ISSUE TITLE
Can't connect to new MongoDB with SSL

### ISSUE THREAD

**Issue by letsgolesco** [compose/transporter#171]
We're hoping to use a new MongoDB 3.2 deployment on Compose and our service depends on a Transporter piping data from MongoDB to an Elasticsearch instance. 

We've set up Oplog access on the deployment and we're trying to use that connection info, but so far it's not working. When we try to connect, we get: 
`cannot create mongo adaptor (ttc-mongo). unable to parse uri (mongodb://:@:/local?authSource=admin&ssl=true), unsupported connection URL option: ssl=true`

When we remove the "ssl=true" option, we get this error: 
`got err reading collection. reissuing query not authorized for query on ttc-prod-main.accounts`

Then I read [this blog post](https://www.compose.io/articles/composes-new-mongodb-and-what-you-need-to-know/) and tried adding the `ssl: {}` option to the pipeline. Now we get this error (with or without `ssl=true` in the connection URI):
`cannot create mongo adaptor (ttc-mongo). no reachable servers`

Any ideas here?

**Comment by codepope** [comment]
What's the actual URI you are using?

(You are right though, you need to lose the &ssl=true and add the ssl:{} in the pipeline...)

**Comment by letsgolesco** [comment]
The actual URI we're using looks like this: 
`mongodb://oploguser:<password>@<ip.address>:<port>/local?authSource=admin`

**Comment by codepope** [comment]
IP address? Not the resolvable host name?

**Comment by letsgolesco** [comment]
It's actually the resolvable host name, provided by the Oplog add-on inside the Compose deployment (looks like `haproxy1234.aws-us-east-x-portal.x.dblayer.com`)

**Comment by codepope** [comment]
Ok, if you could help out and give us the mongodb part of your config.yaml as something doesn't seem right.

**Comment by letsgolesco** [comment]
Sure, it looks like this (don't want to post the exact info publicly):
```yaml
nodes:
 mongo:
    type: mongo
    uri: mongodb://oploguser:<password>@haproxy1234.aws-us-east-x-portal.x.dblayer.com:12345/local?authSource=admin
    tail: true
```

And our application pipeline looks like this:
```javascript
Source({
    name: 'mongo',
    namespace: 'database-name./^(accounts|groups|opportunities)$/',
    ssl: {}
}).transform({
    filename: './transformer.js',
    namespace: 'database-name./^(accounts|groups|opportunities)$/'
}).save({
    name: 'elasticsearch',
    namespace: 'database-name./^(accounts|groups|opportunities)$/'
});
```

**Comment by letsgolesco** [comment]
To sum up the issue, right now when I include the `ssl: {}` option in the pipeline, I can't connect to the MongoDB at all, as I get:
`cannot create mongo adaptor (ttc-mongo). no reachable servers`

However, when I exclude that ssl option I seem to be able to at least hit the MongoDB, but `oploguser` doesn't seem to have permission to query on the database/collections I need to transport from:
`got err reading collection. reissuing query not authorized for query on ttc-prod-main.accounts`

When I connect directly to the MongoDB as `oploguser` via terminal, I can access the Oplog just fine but the user is restricted to the `local` database. I'm not sure how this would work for the initial transportation of existing documents...

Maybe the solution could be to have two connections to the mongodb in the `config.yaml`, one with oplog permissions to transport updates in real-time (i.e. with `tail: true`), and another for the initial transportation of existing documents (i.e. without `tail: true`).

It seems like this isn't currently possible however, as the initial transportation still occurs when you specify the `tail: true` option.

**Comment by codepope** [comment]
I suggest you take this to compose support where we can discuss the specifics of your connection strings  and the configuration of your database.

We have the transporter reading and tailing databases in house.

**Comment by letsgolesco** [comment]
I was pointed here from Compose support, but I'll take it back there if we need to dive into my specific deployment
