### ISSUE TITLE
Timeouts on large collections

### ISSUE THREAD

**Issue by ebaizel** [compose/transporter#175]
We are seeing timeouts trying to transport a very large collection from Mongo 3.0 to a new 3.2 WiredTiger instance.  The collection has 200 million documents at around 80 GB.  

We ran it three times and each time it got to different levels of completion before dying, and then it does not restart.

```
actual ip info changed
transporter: ERROR: mongodb error (read tcp 11.11.11.11:11111->22.22.22.22:22222: i/o timeout)
```

Any suggestions on how to complete a transfer like this?  Is there a way to either:
- restart from where it left off
- specify a query on the source.  it's a mostly write-only collection so we could say only bring in documents created since the last document that was copied over

Thanks.

**Comment by jipperinbham** [comment]
@ebaizel can you try running transporter from the `experimental` branch? We've added a socket timeout option that appears to have resolved the issue but would like to have others outside of Compose test it as well.

**Comment by ebaizel** [comment]
see my comment in #164

**Comment by jipperinbham** [comment]
👍  closing this as a duplicate
