### ISSUE TITLE
Support for ES 2.2.0

### ISSUE THREAD

**Issue by apanimesh061** [compose/transporter#176]
Does this version of transporter work with ES 2.2.0?

**Comment by anortef** [comment]
Nope if you use mongodb as a source. It retrieves the _id and passes it on the body and in the params of the request resulting on an error.

**Comment by jstreger** [comment]
Is there anything similar to this project that would work for ES 2.x?

**Comment by anortef** [comment]
I've forked it here: https://github.com/anortef/transporter and started changing things to make it work with ES 2.x and some mongo improvements too.

Why I'm not doing PR? because this project feels pretty much abandoned so...

**Comment by jipperinbham** [comment]
closing this in favor of https://github.com/compose/transporter/issues/209
