### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by connorblack** [compose/transporter#177]
When installing on ubuntu 14.04, go version go1.2.1 linux/amd64, following [this guide](https://www.digitalocean.com/community/tutorials/how-to-sync-transformed-data-from-mongodb-to-elasticsearch-with-transporter-on-ubuntu-14-04), the following error occurs on this command: 

```
root@host:~/go/src/github.com/compose/transporter# go get -a ./cmd/...
# github.com/araddon/gou
../../araddon/gou/testutil.go:26: syntax error: unexpected range, expecting {
../../araddon/gou/testutil.go:34: non-declaration statement outside function body
../../araddon/gou/testutil.go:35: non-declaration statement outside function body
../../araddon/gou/testutil.go:36: syntax error: unexpected }
# gopkg.in/dancannon/gorethink.v1
../../../gopkg.in/dancannon/gorethink.v1/connection.go:59: undefined: tls.DialWithDialer
```

**Comment by codepope** [comment]
That article is somewhat misleading as it uses an older way of building the Transporter. You'll want an up to date Go (1.4 or later) and then use the build instructions on the README here - https://github.com/compose/transporter 

Or you can skip the entire process and go here https://github.com/compose/transporter/releases and download a binary release.

**Comment by martyychang** [comment]
I'm getting a very similar error when building the current `master` branch (c5aa66a27f80f974de504d8a3917b5b2cb7651ba) on Ubuntu Server 14.04 LTS.

```
$ pwd
/home/ubuntu/Workspace/golang/src/github.com/compose/transporter
$ go version
go version go1.2.1 linux/amd64
$ $GOPATH/bin/godep restore
$ $GOPATH/bin/godep go build -a ./cmd/...
# gopkg.in/dancannon/gorethink.v1
Godeps/_workspace/src/gopkg.in/dancannon/gorethink.v1/connection.go:57: undefined: tls.DialWithDialer
# github.com/compose/transporter/pkg/transporter
pkg/transporter/pipeline.go:155: syntax error: unexpected range, expecting {
pkg/transporter/pipeline.go:158: syntax error: unexpected }
pkg/transporter/pipeline.go:187: syntax error: unexpected range, expecting {
pkg/transporter/pipeline.go:190: syntax error: unexpected }
godep: go exit status 2
```

**Comment by trinchan** [comment]
@martyychang please use golang > 1.4. `tls.DialWithDialer` is available as of golang 1.3

**Comment by martyychang** [comment]
@trinchan thank you for the pointer. I had downloaded and installed the [latest Go source](https://golang.org/doc/install?download=go1.6.2.linux-amd64.tar.gz) for Linux, but apparently I had another installation of go on my server that I didn't know about. After fixing the symlink for */usr/bin/go* I was able to build Transporter successfully.

```
$ go version
go version go1.6.2 linux/amd64
```

**Comment by jipperinbham** [comment]
issue cleanup
