### ISSUE TITLE
undefined: tls.DialWithDialer

### ISSUE THREAD

**Issue by martyychang** [compose/transporter#186]
Trying to build [the v0.1.1 release](https://github.com/compose/transporter/releases/tag/v0.1.1) on Ubuntu Server 14.04, but failing due to what appears to be a problem in a dependent repo.

```
$ $GOPATH/bin/godep go build -a ./cmd/...
# gopkg.in/dancannon/gorethink.v1
Godeps/_workspace/src/gopkg.in/dancannon/gorethink.v1/connection.go:57: undefined: tls.DialWithDialer
godep: go exit status 2
```

**Comment by trinchan** [comment]
@martyychang [tls.DialWithDialer](https://golang.org/src/crypto/tls/tls.go?s=3222:3314#L89) is part of the standard library as of go 1.3. We recommend go 1.4 or higher for transporter.

**Comment by martyychang** [comment]
Thanks for the pointer, @trinchan . Your comment pointed me [to a problem](https://github.com/compose/transporter/issues/177#issuecomment-216998922) that upon resolution allowed me to build Transporter successfully.
