### ISSUE TITLE
adaptor 'mongo' not found in registry

### ISSUE THREAD

**Issue by josgilmo** [compose/transporter#187]
I have been trying to use transporter for sync MongoDB to  ElasticSearch and I'm having a problem.

I follow step by step the instructions explained in http://stackoverflow.com/questions/21634527/scrapy-mongodb-and-elasticsearch-synchronization, but when I execute the run command

transporter run --config ./test/config.yaml ./test/application.js

I get the response "adaptor 'mongo' not found in registry" in the command line.

any hint?

**Comment by banks** [comment]
This is an unfortunate issue caused by a recent refactor - try `mongodb`.

**Comment by josgilmo** [comment]
I tried, and the output by command line it's something like 

"Mongo Config {URI:mongodb://localhost/shopi Namespace:foo.bar Ssl:<nil> Timeout: Debug:true Tail:false Wc:0 FSync:false Bulk:false}"
adaptor 'mongodb' not found in registry

**Comment by codepope** [comment]
Could you show us the config.yaml you are using (redacted appropriately of course)

**Comment by josgilmo** [comment]
@codepope, It's happening to me even with the test configuration

with the files test/config.yaml and test/application.js in the repository.

**Comment by rishiloyola** [comment]
Initially I was also facing the same problem. but I think so their master branch is not updated yet. Use v0.1.1. It is working for me.

**Comment by blackdynamo** [comment]
I am having the same issue and I am using v0.1.1 like suggested.

> adaptor 'mongo' not found in registry

**Comment by franco104** [comment]
I am having the same issue. Has there been any status update about this?

**Comment by bienko** [comment]
Continue to have this issue as well.

**Comment by rishiloyola** [comment]
Checkout this repo, I am mainting it and trying to add new features.
To run it locally must follow its build notes. Let me know if it is not working for you.
[transporter](https://github.com/appbaseio/transporter)

**Comment by trinchan** [comment]
this, and other bug fixes, has been resolved in the [experimental build](https://github.com/compose/transporter/tree/experimental) which will be made stable soon. check out the releases section for a pre-release binary. if you need to use the master build, try using `mongodb` in place of `mongo`. it was errantly renamed and has been reverted in the experimental build. leaving this issue open until merge into master though.

**Comment by bienko** [comment]
Thanks, can confirm that it's now working using the experimental build.

**Comment by huyhoang1990** [comment]
I had the same issue, How can i resolve this problem ?

**Comment by jipperinbham** [comment]
@huyhoang1990 we suggest using the [experimental branch](https://github.com/compose/transporter/tree/experimental) right now as we plan to merge these changes into master soon.
