### ISSUE TITLE
Guide for continuous server

### ISSUE THREAD

**Issue by lorensr** [compose/transporter#192]
Compose support says not to use this anymore:

![image](https://cloud.githubusercontent.com/assets/251288/15163981/d97980fe-16d9-11e6-9eab-5ce5ee3f19e8.png)

This guide doesn't apply: https://github.com/compose/transporter#os-x because I need a continuous transporter running on a server somewhere. A set of steps for getting this running on AWS would be great! 

Also, in the past it has crashed whenever there's a stepdown. How do I get it to auto restart, or is there a way it can notify me when it's crashed, so that I can manually restart? Thanks!

cc @WesleyDavid @sneaks03

**Comment by jipperinbham** [comment]
@lorensr we've just published a new release [v0.1.2](https://github.com/compose/transporter/releases/tag/v0.1.2) and have published a docker image https://quay.io/repository/compose/transporter?tab=tags if you'd like to try running it that way.
