### ISSUE TITLE
Getting an error during installation with elasticsearch 2.3.3

### ISSUE THREAD

**Issue by mandeepm91** [compose/transporter#193]
When I run the command 

```
go get -a ./cmd/...
```

I get the following error:

```
pkg/adaptor/elasticsearch/elasticsearch.go:142: too many arguments in call to e.indexer.Delete
pkg/adaptor/elasticsearch/elasticsearch.go:145: too many arguments in call to e.indexer.Index
```

**Comment by carlosmirandadiaz** [comment]
Same error, someone have the answer for this?

**Comment by trinchan** [comment]
I believe there is a conflict with the installed version of elastigo on your system and transporter. Transporter uses `godep` in the master branch and vendors dependencies in the `experimental` branch. Please try building from source by cloning and using godep.

**Comment by rg-openerp** [comment]
@mandeepm91 There is some issue in version of Go and transporter. to resolve this issue you can optionally go to line number **142 and 145** of file  **pkg/adaptor/elasticsearch/elasticsearch.go** under **e.indexer.Delete** remove extra parameter **false** and  same do for **Index** method in line 145.

Hope it will work..
Thanks

**Comment by jipperinbham** [comment]
closing this in favor of https://github.com/compose/transporter/issues/209
