### ISSUE TITLE
Adaptor 'transformer' not found in registry

### ISSUE THREAD

**Issue by carlosmirandadiaz** [compose/transporter#196]
I got this issue when i try to transform the data from the example from DigitalOcea

My application.js is:

var pipeline = Source({name:"localmongo", namespace:"foo.bar"})
.transform({filename: "transformers/addFullName.js"})
.save({name:"es", namespace:"foo.bar"});

My config.yaml is:
# api:
# interval: 60s
# uri: "http://requestb.in/13gerls1"
# key: "48593282-b38d-4bf5-af58-f7327271e73d"
# pid: "something-static"

nodes:
  localmongo:
    type: mongodb
    uri: mongodb://localhost/foo
  es:
    type: elasticsearch
    uri: http://localhost:9200/
  timeseries:
    type: influx
    uri: influxdb://root:root@localhost:8086/compose
  debug:
    type: file
    uri: stdout://
  foofile:
    type: file
    uri: file:///tmp/foo

And my transformers/AddFullName.js is:

module.exports = function(doc) {
  doc._id = doc._id['$oid']; 
  doc["fullName"] = doc["firstName"] + " " + doc["lastName"];
  return doc
}

**Comment by jstreger** [comment]
add namespace:"foo.bar" after your .transform line

**Comment by raz-l** [comment]
it worked @carlosmirandadiaz ?

**Comment by huyhoang1990** [comment]
I had the same issues. How can i resolve this problem ?

**Comment by jipperinbham** [comment]
@carlosmirandadiaz what version of transporter are you running?

**Comment by jipperinbham** [comment]
closing this as it looks to be a configuration error with either missing the `namespace` variable or defining the wrong path to the transform file.
