### ISSUE TITLE
transporter is giving error while indexing to elasticsearch

### ISSUE THREAD

**Issue by sc-ravagr** [compose/transporter#198]
Hi,

I have followed all the steps as given in 

https://www.digitalocean.com/community/tutorials/how-to-sync-transformed-data-from-mongodb-to-elasticsearch-with-transporter-on-ubuntu-14-04

Now, when I execute :- transporter run --config config.yaml application.js

It gives the error as

transporter: ERROR: transformer error (TypeError
    at <unknown>
    at <unknown>
)
transporter: ERROR: transformer error (TypeError
    at <unknown>
    at <unknown>
)
transporter: ERROR: transformer error (TypeError
    at <unknown>
    at <unknown>
)
transporter: ERROR: transformer error (TypeError
    at <unknown>
    at <unknown>
)

Its killing.

**Comment by Chintanvpatel** [comment]
@sc-ravagr , I was facing the same issue with tutorial. I think document is outdated. I updated as below

```
module.exports = function(doc) {
  doc._id = doc.data._id['$oid']; 
  doc["fullName"] = doc.data["firstName"] + " " + doc.data["lastName"];
  return doc
}
```
The difference is you will get all keys inside "data" key

Hope it helps.

**Comment by jipperinbham** [comment]
closing this as it looks to be a issue between versions of transporter where the document sent to transformers was changed.
