### ISSUE TITLE
Transporter looking for documents from the wrong database

### ISSUE THREAD

**Issue by letsgolesco** [compose/transporter#200]
### Background

I have multiple databases, (e.g. `database1` and `database2`). I have 2 transporters running, one for each database (e.g. the first has namespace `database1./collection-regex/`, the second has namespace `database2./collection-regex/`).
### Problem

I've been seeing a ton of errors from my transporters that look like this:
`ERROR: Mongodb error (my-database.wrong-collection ObjectIdHex("57d6c1bd39259115008194d1") not found)`

What's happening here is that the ObjectId in question actually does exist, but in the wrong database.

It seems that both transporters react to oplog entries for each database, despite the namespace specifications.

I can see the oplog entries, and they have the correct `ns` (namespace) property specified (e.g. `database1.collection1`).

Is Transporter ignoring the `ns` property of the oplog documents, or am I doing something wrong here?

**Comment by AndrewBarba** [comment]
I can confirm I am seeing similar results

**Comment by jipperinbham** [comment]
@letsgolesco what version of transporter are you experiencing this issue with?

**Comment by jipperinbham** [comment]
looking back through changes, I _*think*_ this was fixed via https://github.com/compose/transporter/commit/abcf94f50233772077d52f81c0dc44b8749c41ef

**Comment by jipperinbham** [comment]
fixed in the latest release [v0.1.2](https://github.com/compose/transporter/releases/tag/v0.1.2)
