### ISSUE TITLE
Restart syncing after crash

### ISSUE THREAD

**Issue by kureikain** [compose/transporter#201]
Hi,

We are syncing two mongodb replicaset. But probably due to our workload, sometimes it crash in midldle with this error:

```
transporter: ERROR: mongodb error (read tcp 10.1.1.120:27017: i/o timeout)
```

It doesn't leave any stack trace in stdout and continue to run with repeated errors output in stderr.

I'm wondering if I restart it again, will it pickup correctly? or Do I have to manually set some oplog timestamp?

**Comment by jipperinbham** [comment]
transporter doensn't currently support the ability to resume a sync after being stopped but some work is already in place to support it with more planned for the near future.

feel free to follow https://github.com/compose/transporter/issues/33 for updates
