### ISSUE TITLE
transporter: CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [x])

### ISSUE THREAD

**Issue by sachq** [compose/transporter#207]
I'm trying to transport 15000 documents from MongDB to Elasticsearch and i'm getting Bulk insertion error. I can't really figure out what the issue is.

* [es-bulk-insertion-err-gist](https://gist.github.com/sachq/11b2d1d3fd081129315af7db89452c15)

**Comment by jipperinbham** [comment]
closing this in favor of https://github.com/compose/transporter/issues/209
