### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by saribmahmood55** [compose/transporter#231]
So I'm trying to transfer data from mongodb to elasticsearch, and with the master branch I was facing the issue of bulk insertion, and now I've tried with the experimental branch. But on the experimental branch I keep getting the concurrent map read and map writes error.

### Relevant config.yaml and application.js:

######config.yaml
nodes:
  remotemongo:
    type: mongodb
    uri: mongodb://remote-login-cred/dbname
    tail: true
  es:
    type: elasticsearch
    uri: http://localhost:9200/
  timeseries:
    type: influx
    uri: influxdb://root:root@localhost:8086/compose
  debug:
    type: file
    uri: stdout://
  foofile:
    type: file
    uri: file:///tmp/foo

#####application.js
Source({name:"remotemongo", namespace:"foo.bar"}).save({name:"es", namespace:"foo.bar"})

### System info:

- Transporter version : Experimental Branch
- OS : Ubuntu

### Reproducible Steps:

facing the error when I try to run the transporter
transporter run --config ./test/config.yaml ./test/application.js

Can anyone help with the issue?

The error log is below
INFO[0000] done iterating collections                    db="dbname"
INFO[0000] iterating...                                  collection=collectionname
fatal error: concurrent map read and map write

goroutine 67 [running]:
runtime.throw(0x10ad900, 0x21)
	/usr/lib/go-1.6/src/runtime/panic.go:547 +0x90 fp=0xc8206a1d48 sp=0xc8206a1d30
runtime.mapaccess2_faststr(0xd77380, 0xc820400bd0, 0xfb30a0, 0x3, 0xc820400bd0, 0xc82050d801)
	/usr/lib/go-1.6/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc8206a1da8 sp=0xc8206a1d48
github.com/compose/transporter/pkg/adaptor/mongodb.(*Reader).iterateCollection.func1(0xc820047b00, 0xc82051ad80, 0xc8203c8120, 0xc82050d520, 0xc820047140)
	/home/ubuntu/go/src/github.com/compose/transporter/pkg/adaptor/mongodb/reader.go:111 +0x464 fp=0xc8206a1f78 sp=0xc8206a1da8
runtime.goexit()
	/usr/lib/go-1.6/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8206a1f80 sp=0xc8206a1f78
created by github.com/compose/transporter/pkg/adaptor/mongodb.(*Reader).iterateCollection
	/home/ubuntu/go/src/github.com/compose/transporter/pkg/adaptor/mongodb/reader.go:136 +0x7b

goroutine 1 [chan receive]:
github.com/compose/transporter/pkg/adaptor/mongodb.(*MongoDB).Start(0xc8201f83c0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/compose/transporter/pkg/adaptor/mongodb/mongodb.go:154 +0x386
github.com/compose/transporter/pkg/transporter.(*Node).Start(0xc820046de0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/compose/transporter/pkg/transporter/node.go:158 +0xdd
github.com/compose/transporter/pkg/transporter.(*Pipeline).Run(0xc82000ac30, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/compose/transporter/pkg/transporter/pipeline.go:115 +0x1c8
main.(*JavascriptBuilder).Run(0xc8203240e0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/compose/transporter/cmd/transporter/javascript_builder.go:299 +0x77
main.(*runCommand).Run(0x15d6a08, 0xc82000a070, 0x3, 0x3, 0x122e3b8)
	/home/ubuntu/go/src/github.com/compose/transporter/cmd/transporter/command.go:120 +0x649
github.com/compose/transporter/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc82019c3c0, 0xc82017eff0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/compose/transporter/vendor/github.com/mitchellh/cli/cli.go:154 +0x56e
main.main()
	/home/ubuntu/go/src/github.com/compose/transporter/cmd/transporter/main.go:24 +0x474

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.6/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.6/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/lib/go-1.6/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/go-1.6/src/os/signal/signal_unix.go:28 +0x37

goroutine 20 [select]:
github.com/compose/transporter/vendor/gopkg.in/mgo%2ev2.(*mongoCluster).syncServersLoop(0xc82018a400)
	/home/ubuntu/go/src/github.com/compose/transporter/vendor/gopkg.in/mgo.v2/cluster.go:394 +0x617
created by github.com/compose/transporter/vendor/gopkg.in/mgo%2ev2.newCluster
	/home/ubuntu/go/src/github.com/compose/transporter/vendor/gopkg.in/mgo.v2/cluster.go:78 +0x1d5

goroutine 33 [sleep]:
time.Sleep(0x37e11d600)
	/usr/lib/go-1.6/src/runtime/time.go:59 +0xf9
github.com/compose/transporter/vendor/gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8203249a0, 0x1)
	/home/ubuntu/go/src/github.com/compose/transporter/vendor/gopkg.in/mgo.v2/server.go:301 +0x1a6
created by github.com/compose/transporter/vendor/gopkg.in/mgo%2ev2.newServer
	/home/ubuntu/go/src/github.com/compose/transporter/vendor/gopkg.in/mgo.v2/server.go:89 +0x165

goroutine 8 [sleep]:
time.Sleep(0x37e11d600)
	/usr/lib/go-1.6/src/runtime/time.go:59 +0xf9
github.com/compose/transporter/vendor/gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8200160e0, 0x1)
	/home/ubuntu/go/src/github.com/compose/transporter/vendor/gopkg.in/mgo.v2/server.go:301 +0x1a6
created by github.com/compose/transporter/vendor/gopkg.in/mgo%2ev2.newServer
	/home/ubuntu/go/src/github.com/compose/transporter/vendor/gopkg.in/mgo.v2/server.go:89 +0x165

**Comment by jipperinbham** [comment]
@saribmahmood55 thanks for the error report, we're pretty sure this was fixed via https://github.com/compose/transporter/pull/227. can you test it out?

**Comment by saribmahmood55** [comment]
perfect, let me pull the changes and check again. Thanks

**Comment by saribmahmood55** [comment]
@jipperinbham so now it's reading records from the mongodb but after getting bulk records each time when it tries to get them into elasticsearch it gives bulk insertion error. Can you help with that?

**Comment by jipperinbham** [comment]
yea... I'm not surprised. I've been working on redoing the elasticsearch adaptor in [209-es-stability](https://github.com/compose/transporter/tree/209-es-stability). would you be able to checkout that branch and test it out? It'd be very helpful to get some feedback from these changes.

**Comment by saribmahmood55** [comment]
yeah sure. Let me do that.

**Comment by saribmahmood55** [comment]
Yeah, so finally success. @jipperinbham with 209-es-stability I'm no longer facing the bulk import elasticsearch error. And everything has been transported from mongodb to elasticsearch successfully.

**Comment by saribmahmood55** [comment]
@jipperinbham I think I spoke to early, so transporter stdout doesn't show the errors but the elasticsearch still having the bulk insertion error. So it starts of properly and elasticsearch keeps logging "update mapping" message but then suddenly after few thousand records elasticsearch start behaving giving out the insertion error. It then starts logging the bulk insertion error.

**Comment by jipperinbham** [comment]
@saribmahmood55 gotcha, couple quetions:

- what version of elasticsearch are you running?
- what is the elasticsearch log showing?
- does it insert any data into elasticsearch? and if so, about how much until you start seeing errors?

**Comment by saribmahmood55** [comment]
So, I'm using elasticsearch 5.1.2 and I've tested it on 5.1.1 the error is the same on both.

And this keeps getting logged in elasticsearch( had to hide some data, though didn't do a good job at it)
<img width="1370" alt="screen shot 2017-01-19 at 3 44 15 pm" src="https://cloud.githubusercontent.com/assets/2581199/22124703/e5554a1e-de5e-11e6-880d-66e4975535a3.png">

So I just checked and I have 490162 docs in mongodb collection and elasticsearch is showing that it indexed 481151 so almost 9000 docs went missing.

Hope it helps.

**Comment by jipperinbham** [comment]
ok, that is very helpful, I've been using elasticsearch `5.0.2` locally so I'll first get updated to the latest to run some tests. 

looking at the elasticsearch log, it looks like there could be an issue with some of the documents having a filed with multiple types. Is it possible for that to be the case?

**Comment by saribmahmood55** [comment]
oh yeah, I just noticed I guess its the issue with my data. I guess I was looking for the bulk insertion error and didn't notice the logs below. Well in that case I think its working fine and the problem is with the data. I'm gonna have a look at the data and try to fix the issue. Thanks

**Comment by saribmahmood55** [comment]
So what's the timeline on all this. Are you gonna pull the changes in the master branch soon or do you want to keep testing it on the experimental branch. Also, are you planning to pull this es-stability into experimental branch?

**Comment by jipperinbham** [comment]
it's one of the remaining items for the v0.1.2 release, you can track the progress of it [here](https://github.com/compose/transporter/milestone/3). 

I expect #233 to be merged into `experimental` soon though.

**Comment by saribmahmood55** [comment]
Perfect, nice. Thanks man. Appreciate all the help.

**Comment by jipperinbham** [comment]
no problem, thanks for providing all the details and testing. I'm going to close this one out but please feel free to re-open it if you run across something new.
