### ISSUE TITLE
Elasticsearch client.Reader support

### ISSUE THREAD

**Issue by jipperinbham** [compose/transporter#247]
it'd be great to be able to support the ability to read/copy data from elasticsearch to other sinks.

**Comment by damiano-vesperini** [comment]
Hello, any news about the support of elasticsearch as a Source adaptor?

**Comment by jipperinbham** [comment]
nothing new to report here really as my focus has been on other areas of transporter lately

it's definitely still something I think is valuable and what to do though so any help here would be great!

**Comment by riccardo-angelilli** [comment]
@jipperinbham any news about Elasticsearch support as a source in Transporter?

**Comment by jipperinbham** [comment]
no update here and it's not something I've planned on working on for the next release.
