### ISSUE TITLE
Transporter does not use config.yaml as default

### ISSUE THREAD

**Issue by codepope** [compose/transporter#253]
## Bug report

Running transporter 0.1.2 requires transporter.yaml not config.yaml as default config name

### Relevant config.yaml and application.js:

N/A 

### System info:

- Transporter version 0.1.2

### What did you expect to happened?

Docs and notes (and even bug report template) still refer to config.yaml

### What actually happened?

rename config.yaml to transporter.yaml and all is good. Needs noting in repository docs.

**Comment by jipperinbham** [comment]
closing this as it was an intentional breaking change.
