### ISSUE TITLE
Documents missing in elasticsearch when transfering from mongodb

### ISSUE THREAD

**Issue by dusnoki** [compose/transporter#262]
### Relevant config.yaml and application.js:
config.yaml:
```
# api:
#   interval: 60s
#   uri: "http://requestb.in/13gerls1"
#   key: "48593282-b38d-4bf5-af58-f7327271e73d"
#   pid: "something-static"
nodes:
  localmongo:
    type: mongodb
    uri: mongodb://localhost/client-name
  es:
    type: elasticsearch
    uri: http://localhost:9200/
  timeseries:
    type: influx
    uri: influxdb://root:root@localhost:8086/compose
  debug:
    type: file
    uri: stdout://
  foofile:
    type: file
    uri: file:///tmp/client-name
```
application.js
`Source({name:"localmongo", namespace:"client-name.leads"}).save({name:"es", namespace:"client-name.leads"});`

### System info:

- Transporter version v0.1.2
- OS Ubuntu 16.04
- DB version(s) mongodb 3.2, elasticsearch 5.2

### Reproducible Steps:

1. transporter run --config ./test/config.yaml ./test/application.js

### What did you expect to happened?
For a while I get this response
`INFO[0003] _bulk flush completed                         executionID=2 path="localmongo/es" succeeeded=1000 took=2663ms version=5 writer=elasticsearch`

### What actually happened?
but after a while only succeeeded = 0-6
`INFO[0169] _bulk flush completed                         executionID=104 path="localmongo/es" succeeeded=0 took=1518ms version=5 writer=elasticsearch`

My mongo collection that needs to be transfered to elasticsearch has 155416 documents... but for some reason only about 79563 are being transfered.

in the end the console gives me 
```
INFO[0867] metrics localmongo records: 155416            path=localmongo ts=1486490263117188173
INFO[0867] metrics localmongo/es records: 155416         path="localmongo/es" ts=1486490263117197289
```
but when I do a call to localhost:9200/client-name/leads/_count
```
{
    "count": 79563,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    }
}
```

I have another collection of 1.200.000+ documents that pass over to elasticsearch without problem

**Comment by jipperinbham** [comment]
@dusnoki thanks for the detailed report! 

it's hard to say why the documents are not making it to ES but can you confirm there's no mixed field types in the data? (i.e. `record_id` is a string in most records but an int in others)

if the elasticsearch response had contained an error, it _should have_ been logged, was there anything in your elasticsearch logs indicating an issue with the inserts?

**Comment by dusnoki** [comment]
I believe I found out the issue
In the elasticsearch error log I got the error 

`limit of total fields [1000] in index [client-name] has been exceeded`

So with a little research found a solution for this problem.
Maybe it will help someone else

```
PUT client-name/_settings
{
  "index.mapping.total_fields.limit": 5000
}
```
@jipperinbham thank you for all your help

**Comment by jipperinbham** [comment]
oh great! I don't think I've ever come across that issue before so glad you were able to figure it out. I'm gonna close this one out but please feel free to re-open if you hit a similar issue.
