### ISSUE TITLE
Information on connecting to Mongo with SSL

### ISSUE THREAD

**Issue by ebaizel** [compose/transporter#264]
## Feature Request

Can you provide documentation/an example for connecting to an SSL enabled Mongo instance?  Our source Mongodb is Compose on WiredTiger 3.2 with SSL.  When I try the config below I get the error:

`oplog access failed, unable to list collections on local database`

```
localmongo1:
  type: mongodb
  uri: mongodb://user:password@aws...com:12345,aws...com:67890/acme
  namespace: acme.users
  ssl: true
  debug: true
```

The user has full access on the `acme` database.

**Comment by ebaizel** [comment]
figured it out.  i needed to enable the oplog addon and then connect with the oplog user.

**Comment by jipperinbham** [comment]
@ebaizel glad you were able to get things sorted! would you mind providing some insight regarding the path you took to try and find a solution/documentation? as well as where you would have expected the documentation to be?

**Comment by ebaizel** [comment]
Sure!  I began by looking for the docs in the main project README and then at `transporter/pkg/adaptor/mongodb`.

I also searched for oplog access and eventually remembered that Compose has an oplog addon, and that's when I got close to solving it.  And then I found this Compose blog post that was really helpful https://www.compose.com/articles/connecting-to-the-oplog-on-the-new-mongodb/

It's still not clear to me what all the options are and how and in which file to set them.  Examples: `bulk`, `ssl`.

I'm now running into issues when _writing_ to the destination if it's a mongo db.  As a simple test, I set up the same source and dest nodes, but when it tries writing I get:

`oplog access failed, unable to list collections on local database`

I'm not using the oplog user since I believe that's a read-only user, but it looks like I need to have oplog access on the destination?

**Comment by ebaizel** [comment]
Also, I really appreciate the help and would be more than happy to submit documentation PRs as I figure this stuff out too if that'd be helpful.

**Comment by jipperinbham** [comment]
thanks for the rundown! 

we definitely have a good bit of work to do around documentation and providing good base configs so any help there is greatly appreciated. 

The error you're seeing now:
```
oplog access failed, unable to list collections on local database
```

means that you've configured the source node with `tail: true` which isn't necessary since it's only going to be used for writes.

**Comment by ebaizel** [comment]
awesome, happy to help where i can.  what's the best way to submit a pr?  i just tried pushing a branch but i don't have writes on this repo.

**Comment by jipperinbham** [comment]
take a look at the [conventions](https://github.com/compose/transporter/blob/master/CONTRIBUTING.md#conventions) section, if it's just markdown/doc changes, a lot of the `go` specific stuff can be ignored.

thanks for helping out!

**Comment by jipperinbham** [comment]
@ebaizel just wanted to check back and see if you needed help with anything for submitting your PR

**Comment by Dshubhambadola** [comment]
@jipperinbham I am new to development and to the compose transporter can you help me how can i sync a single collection data to elasticsearch not the whole mongo db `var source = mongodb({
  "uri": "${MONGODB_URI}"
  // "timeout": "30s",
  // "tail": false,
  // "ssl": false,
  // "cacerts": ["/path/to/cert.pem"],
  // "wc": 1,
  // "fsync": false,
  // "bulk": false,
  // "collection_filters": "{}",
  // "read_preference": "Primary"
})

var sink = elasticsearch({
  "uri": "${ELASTICSEARCH_URI}"
  // "timeout": "10s", // defaults to 30s
  // "aws_access_key": "ABCDEF", // used for signing requests to AWS Elasticsearch service
  // "aws_access_secret": "ABCDEF" // used for signing requests to AWS Elasticsearch service
  // "parent_id": "elastic_parent" // defaults to "elastic_parent" parent identifier for Elasticsearch
})

t.Source("source", source, "/.*/").Save("sink", sink, "/.*/")
` 
This is my pipeline file

**Comment by Dshubhambadola** [comment]
MONGODB_URI='mongodb://localhost/testDb.newBee/' 
ELASTICSEARCH_URI='http://localhost:9200/flos'
