### ISSUE TITLE
cannot find package "context" 

### ISSUE THREAD

**Issue by kishorevarma** [compose/transporter#274]
I am getting below error when I am building.

>  pkg/adaptor/elasticsearch/clients/v1/writer.go:4:2: cannot find package "context" in any of:
    /go/src/github.com/compose/transporter/vendor/context (vendor tree)
    /usr/local/go/src/context (from $GOROOT)
    /go/src/context (from $GOPATH)

I don't know "go" language, but I am thinking its the problem with path, it would be 
```"golang.org/x/net/context"``` instead of ```"context"```,  I might be wrong.

OS: Linux 0093b04bc75f 4.9.8-moby #1 SMP Wed Feb 8 09:59:13 UTC 2017 x86_64 GNU/Linux
Branch: Master

Reproducing steps:
1) docker run -it golang:1.6
2) Follow the installation steps from read me

Its not happening when I tried in mac os

**Comment by kishorevarma** [comment]
I found the solution, I have to build in the following way for linux
```GOOS=linux GOARCH=amd64 go build -v github.com/compose/transporter/cmd/transporter/
```

**Comment by jipperinbham** [comment]
you'll need to use go 1.7 locally to build

**Comment by kishorevarma** [comment]
Thanks @jipperinbham , its working now.
