### ISSUE TITLE
Copy Indexes an Mongodb document validation rules

### ISSUE THREAD

**Issue by ansarizafar** [compose/transporter#313]
## Feature Request

As discussed in another issue, In my opinion, transporter must copy indexes and MongoDB document validation rules. Please add this feature.

**Comment by jipperinbham** [comment]
@ansarizafar thanks for opening the issue!

I've been convinced that this is something we can likely handle so I'll slate it for next month's release and hopefully we can get to it.

**Comment by aztlan2k** [comment]
Just wondering if any progress was made on copying of indexes?

**Comment by jipperinbham** [comment]
I haven't gotten to this yet, it is one of the features planned for the `v0.5.0` release
