### ISSUE TITLE
Automate SSL setting

### ISSUE THREAD

**Issue by codepope** [compose/transporter#319]
Version: 0.3.0

## Feature Request

When "?ssl=true" is present in the connection string for MongoDB, automatically remove the "?ssl=true" from the string and set the ssl:true property to true.

This would allow simple cut and pasting of URLs without modification into env vars and pipeline.js

**Comment by keremgocen** [comment]
Requesting permission to jump onboard and tackle this, captain!

**Comment by jipperinbham** [comment]
nice! I vaguely remember thinking it could be accomplished in https://github.com/compose/transporter/blob/f6b0a34da6dc6c1d08b6ec53a268c131e9332898/adaptor/mongodb/client.go#L112-L121 with a call to `WithSSL(true)(c)`
