### ISSUE TITLE
Specifying DB name in Mongodb adaptor

### ISSUE THREAD

**Issue by ebaizel** [compose/transporter#338]
### Relevant pipeline.js:

```
var source = mongodb({
  "uri": "mongodb://user:password@boxname.dblayer.com:12345/local?authSource=admin",
  "ssl": true
})

t.Source("source", source, "acme.users").Save("sink", sink)
```

### System info:

- Transporter version
 3.0
- OS
 Linux
- DB version(s)
 Mongo 3.2

### Reproducible Steps:

Just switching to the new 3.0 transporter.  How can I specify the name of my Mongodb database, when I also want to tail the oplog?  Before, I'd set up the mongo url to go to /local so that the tailing could continue, and a namespace of `acme.users` where `acme` is my company and `users` is the collection i want to copy over.

I've tried putting it in the namespace param on the Source but it looks like it's still reading from the local db when I run it.

```
INFO[0000] done iterating collections                    db=local
INFO[0000] Read completed                                db=local
```

**Comment by jipperinbham** [comment]
hey @ebaizel, can you try the following?

```javascript
var source = mongodb({
  "uri": "mongodb://user:password@boxname.dblayer.com:12345/acme?authSource=admin",
  "ssl": true,
  "tail": true
})

t.Source("source", source, "/^users$/").Save("sink", sink)
```

**Comment by ebaizel** [comment]
i get:
`connection error, server returned error on SASL authentication step: Authentication failed.`

if i remove the `authSource=admin` I get:
`oplog access failed, unable to list collections on local database`

**Comment by jipperinbham** [comment]
ok, I was curious about the `authSource` bit and assume this is using a Compose MongoDB deployment?

The `oplog access failed` error indicates the user you provided does not have access to the oplog and needs to have it explicitly granted with a role grant.

**Comment by ebaizel** [comment]
yup it's a compose mongodb deployment.  afaik only the `oploguser` that is displayed within the Add Ons section has access to the oplogs, and since we do need to tail we'll need to have access to it.

could we grant oplog access to our other user?

**Comment by jipperinbham** [comment]
ok, I'll test some things out on my account and see where the sticking point is. 

I'll try and get to it tonight but it may take me a day or so before I'll have sufficient time to dig into it.

**Comment by ebaizel** [comment]
thanks, let me know if i can help with testing or anything.

**Comment by jipperinbham** [comment]
ok, I was able to use transporter on a compose mongodb deployment with the oplog add-on enabled, here's my `pipeline.js`:

```javascript
var source = mongodb({
  "uri": "mongodb://oploguser:REDACTED@gcp-us-east1-cpu.2.dblayer.com:15643/enron?authSource=admin",
  "tail": true
})

var sink = mongodb({
  "uri": "mongodb://10.0.0.47:27017/sink_database"
})

t.Source("source", source).Save("sink", sink)
```

**Comment by jipperinbham** [comment]
@ebaizel any update here?

**Comment by ebaizel** [comment]
i just tested it out with swapping `local` with our db name and it looks to be working great.  haven't verified it's tailing yet as we're still moving over the older data.

**Comment by jipperinbham** [comment]
@ebaizel ping

**Comment by jipperinbham** [comment]
closing this out but feel free to reopen if the it's still an issue

**Comment by sashaaKr** [comment]
@ebaizel You saved my day by your example
