### ISSUE TITLE
Add Gitter for composer/transporter

### ISSUE THREAD

**Issue by remotevision** [compose/transporter#345]
This is a simple suggestion to add a `gitter room` for `transporter`. I would like to collaborate with others that are developing more complex pipelines and realize Github issues are not the place to do it.

https://gitter.im

**Comment by jipperinbham** [comment]
:+1: been meaning to set this up for a while now

**Comment by jipperinbham** [comment]
fixed via https://github.com/compose/transporter/commit/7806cecf6aa46040f43963adbc7554386769a8ad
