### ISSUE TITLE
pick function logs are too verbose

### ISSUE THREAD

**Issue by kiavashps** [compose/transporter#361]
## Problem
The `pick()` function logs out `message.data` before and after the transformation, with `log.level=info`.

This causes a problem for me where the logs become almost double the size of the data I'm transferring, which in my case is 100's of GB. I could change `log.level` to `error`, but I need the metric logs, which are also `info` logs, to track progress.

I also realized this logging seems inconsistent with the other functions (`omit`, `rename`, `skip`, etc...) which don't log anything.

### Proposed Options
I'm not sure what the best or right solution is here, but these are some possible options I came up with:
- change the log level from info to debug
- remove addition `msg` property of 'picking...' and '...picked'
- remove logs from pick altogether

I can submit a PR once I get feedback on the right solution.

**Comment by jipperinbham** [comment]
@kiavashps thanks for the report! 

I'd say change the log level from `info` to `debug` as it was definitely put in place for debugging purposes.

**Comment by kiavashps** [comment]
awesome! will do.
