### ISSUE TITLE
Elasticsearch parent/child relationship

### ISSUE THREAD

**Issue by dphung20** [compose/transporter#374]
Hi there

Wonder if there is a way to define a parent when syncing from mongo to elastic search. I could not find any informations relating to this topic.  How do I go about syncing a child doc with a parent doc

Elastic mapping
`mappings: {
    family: { ... },
    container: {
       _parent: { type: 'family' },
      ...
    }
 }
`

example data
`Family: {
 id: 1,
 name: 'familyName'
 ...
}
`
`Container: {
 id: 100,
 familyId: 1,
 ...
}
`

Here is the basic pipeline i'm using
var source = mongodb({
  "uri": "${MONGODB_URI}"
})

var sink = elasticsearch({
  "uri": "${ELASTICSEARCH_URI}"
})
t.Source("source", source, "/family|container/").Save("sink", sink, "/.*/");`

**Comment by jipperinbham** [comment]
thanks for the detailed report! I'm thinking adding the `rename` function will handle this case. Can you try the following:

```
var source = mongodb({
"uri": "${MONGODB_URI}"
})

var sink = elasticsearch({
"uri": "${ELASTICSEARCH_URI}"
})
t.Source("source", source, "/family|container/")
  .Transform(rename({"field_map": {"familyId":"parent"}}), "/container/")
  .Save("sink", sink, "/.*/");
```

**Comment by dphung20** [comment]
thanks for the reply, unfortunately that doesn't seem to work.  The only records created are the ones for Family and not containers.  I can see the records being process when I use the pretty({}) transform and the field name "familyId" is being rename to "parent":.

``` 
 t.Source("source", source, "/family|container/")  
  .Transform(rename({"field_map": {"familyId":"parent"}}), "/container/")  
  .Transform(pretty({}))
  .Save("sink", sink, "/.*/");
```

the data 
```
Family: { id: 1, name: 'familyName' ... }
Container: { id: 100, parent: 1, ... }
```

**Comment by jipperinbham** [comment]
sorry, after digging into the docs for parent/child associations in elasticsearch, we'll have to make some changes to transporter to support it. today, it makes a naive assumption about the structure and fields. 

at a minimum, we'll need to expose configuration options for what field the `id` should come from and if a `parent` association should be used. both of those config options would need to be namespace scoped. 

is this something you'd be about to help with? also, what version of elasticsearch are you targeting?

**Comment by dphung20** [comment]
The version of elastic i'm using is 5.4.  I haven't done any go programming so I'm not sure how helpful I will be.  I assume adaptor/elasticsearch/clients/v5/writer.go is the file I need to look at right?  I'll try digging into the code a bit and read up on the go programming language.  Can you point me to which file or files I should be looking into.

adaptor/elasticsearch/clients/v5/writer.go: line 92 
```
elastic.NewBulkIndexRequest().Index(w.index).Type(indexType).Id(id).Doc(msg.Data())
```
this seems like the code where I would need to add: .Parent() after the Id function but I'm not sure how to go about passing in the additional information needed.

**Comment by jipperinbham** [comment]
yea, you're definitely on the right track

so, the following bit of code 
```go
br = elastic.NewBulkIndexRequest().Index(w.index).Type(indexType).Id(id).Doc(msg.Data())
```
returns the `*BulkIndexRequest` type so you could have an if statement to check for the presence of a `parent` field in `msg.Data()` (similar to https://github.com/compose/transporter/blob/master/adaptor/elasticsearch/clients/v5/writer.go#L80) and do the following:
```go
br.Parent(msg.Data()["parent"].(string))
```

**Comment by jipperinbham** [comment]
addressed via https://github.com/compose/transporter/pull/406
