### ISSUE TITLE
resuming read looks broken from mongdb to Elasticsearch

### ISSUE THREAD

**Issue by beatsuser** [compose/transporter#375]
I am using the resuming functionality from v0.4.0, but that seems not working as expected.
I am sync from mongodb to elasicsearch.
I run as following config:
t.Config({"log_dir":"/data/transporter"}).Source("source", source, "/.*/").Save("sink", sink, "/.*/")

Here is step:
1)	./transporter run pipeline.js
The first time run will send all data from mongodb to ES, then quit. I see all data in ES.
I checked following:
./transporter xlog -log_dir=/data/transporter/ current
261048
./transporter offset -log_dir=/data/transporter/ list
+------+--------+
| SINK | OFFSET |
+------+--------+
| sink | 261048 |

This looks correct so far

2)	Run again: ./transporter run pipeline.js
./transporter xlog -log_dir=/data/transporter/ current 
261099
./transporter offset -log_dir=/data/transporter/ list
+------+--------+
| SINK | OFFSET |
+------+--------+
| sink | 261048 |
The sink number keep the same, and not updated.

3)	Run again: ./transporter run pipeline.js
The it will report error:
NFO[0002] existing messages in commitlog, checking writer offsets...  name=source newestOffset=261100 oldestOffset=0 path=source type=mongodb
INFO[0002] offsetMap: map[clusterstatus:235759 systemstatus:260842 zkservers:261048 arcusalarm:2002]  name=sink path=source type=mongodb
INFO[0002] adaptor Listening...                          name=sink path="source/sink" type=elasticsearch
INFO[0002] searching segments                            num_segments=3 offset=261048
INFO[0002] boot map[source:mongodb sink:elasticsearch]   ts=1495696884016045320
INFO[0003] found offset position                         offset=261048 position=92693400
INFO[0003] waiting for all children to resume...         name=source path=source type=mongodb
INFO[0003] adaptor Resuming...                           name=sink path="source/sink" type=elasticsearch
INFO[0003] still resuming...                             log_offset=261099 name=sink offset=261048 path="source/sink" percent_complete=99.98046717911598 type=elasticsearch
INFO[0003] offset of message sent down pipe matches newestOffset  name=sink path="source/sink" type=elasticsearch
INFO[0003] all messages sent down pipeline, waiting for offsets to match...  name=sink path="source/sink" timeout=1m0s type=elasticsearch
INFO[0003] checking if offsets match                     name=sink path="source/sink" type=elasticsearch
INFO[0003] offsets did not match, checking again in 5 seconds...  name=sink newestOffset=261099 path="source/sink" sink_offset=261048 type=elasticsearch

**Comment by jipperinbham** [comment]
thanks for the report! 

I assume you're not using the `tail` option for the `source` mongodb adaptor?

what were the logs after running the 2nd time?

you state it errors on the third run but I don't see anything in the log snippet provided? 

what is the database version you're targeting for MongoDB and elasticsearch?

**Comment by jipperinbham** [comment]
@beatsuser were you about to figure out what was going on or are you still seeing the issue?

**Comment by vinay2294** [comment]
@jipperinbham i came across the same issue. It seems like it is an issue with go channels.
