### ISSUE TITLE
Delete document in Elasticsearch with terms

### ISSUE THREAD

**Issue by adrichampre** [compose/transporter#376]
I use transporter to transfert documents from mongo to ES. It works great but I have a problem. Indeed, in mongo I use a tag dateDeleted to keep tracks on removal documents. 
I don't want to transfert a document with a dateDeleted in ES. How can I use your tool to manage this issue? My problem is not to filter the document but to remove it in ES when dateDeleted appears. 
I try to run a ES query when the transform process in transporter detect an dateDeleted element. But it doesn't seem to work because I can't use a javascript require. Do you have an idea?

**Comment by jipperinbham** [comment]
sorry for the delay in responding

It's possible you could use one of the JS transform functions (`goja` or `otto`) to check for the existence of the `dateDeleted` field and if it's present, change the `op` to the value of `s` (which result in the message getting skipped).

Right now, the JS VM is very bare bones and not really capable of doing complex operations (like querying a database) but we are continuing to look at ways to provide access to the adaptors via the transformers.

**Comment by adrichampre** [comment]
I succeeded to solve my problem by changing the value of `op` to `delete`. 

Thanks for the help.
