### ISSUE TITLE
Failing to connect to elasticsearch

### ISSUE THREAD

**Issue by SamBartrum** [compose/transporter#377]
I am trying to use transporter to connect to an AWS Elasticsearch instance. I'm getting a panic error of the form: 

panic: Panic at 40: unable to determine version from .... bad status code: 403

I've tested the AWS credentials and URI by signing an Elasticsearch request with them and they seem to be working ok.

My Elasticsearch sink config is of the form:

var sink = elasticsearch({
    'uri': 'URI',
    'aws_access_key': 'AWS_ACCESS_KEY',
    'aws_access_secret': 'AWS_ACCESS_SECRET'
})

I'm using the latest (v0.4.0) darwin binary release.

**Comment by SamBartrum** [comment]
After some investigation, it seems that the problem might be in the determineVersion function in adaptor/elasticsearch/elasticsearch.go. To get the Elasticsearch version you still need to sign the request with the AWS access key and secret access key, which doesn't seem to be being done in the code? If you don't sign this request you just get back a 403. Unless I'm missing something?

**Comment by aviaryan** [comment]
I just went through the code and `determineVersion` doesn't seem to have to do anything with AWS credentials. That being said you will have to put the full ElasticSearch cluster url with username:password in the `uri` field. Are you doing that? 
Another way to test this is by sending a GET request to `uri`. It should return ElasticSearch cluster details with its version. If not, then it won't work with transporter. 
```
curl -XGET $uri
```

**Comment by SamBartrum** [comment]
Thanks for the reply. Right ok. I'm confused as to why you need to provide a username and password in the uri (as far as I'm aware AWS does not provide basic auth to Elasticsearch out of the box?) and why the request is not just signed with the AWS access/secret keys.

**Comment by jipperinbham** [comment]
@SamBartrum thanks for the bug report and thanks @aviaryan for helping dig into the `determineVersion` code.

This is definitely a bug and just an oversight on my part when writing the `determineVersion` code. I've added the `bug` label to this and I can definitely look into with the next release (i.e. `v0.5.0`) but if either of your are comfortable to work on the change, I'm more than happy to provide any feedback on a PR.
