### ISSUE TITLE
init : adaptor 'postgresql' did not provide a sample config

### ISSUE THREAD

**Issue by snowch** [compose/transporter#387]
## Bug report

```
$ ./transporter-0.4.0-rc.1-darwin-amd64 init postgresql rabbitmq
Writing pipeline.js...
adaptor 'postgresql' did not provide a sample config
```

### Relevant pipeline.js:

pipeline.js was empty

### System info:

- 0.4.0-rc.1
- OS/X 10.12.4

### Reproducible Steps:

1. ./transporter-0.4.0-rc.1-darwin-amd64 init postgresql rabbitmq

### What did you expect to happened?

Expected a pipeline.js to be created and populated.

### What actually happened?

pipeline.js was created but not populated.

**Comment by snowch** [comment]
I was reading the README in the repo top to bottom.  The list of adapters shows 'postgresql'.  After reading further down the page, I see the `transporter about` which shows 'posgres'.

Maybe the `transporter about` section of the README should be moved before the `transporter init` section?

**Comment by jipperinbham** [comment]
thanks for the report, what you've suggested makes sense and any references to `postgresql` should be changed to `postgres` for consistency/accuracy
