### ISSUE TITLE
Specifying read preference for mongo connection

### ISSUE THREAD

**Issue by SamBartrum** [compose/transporter#392]
I don't think transporter supports specifying the read preference for the mongo connection. Is this correct? There is no option to set this in the connection config and including readPreference in the mongo URI results in, for example:

`Invalid URI .... unsupported connection URL option: readPreference=secondary`

I believe this is because you are using mgo to parse the URI for the settings, but I don't think that mgo supports getting the read preference from the URI. Is this correct?

**Comment by jipperinbham** [comment]
that's correct, we don't currently set or expose the read preference for the mongodb adaptor but I don't think it'd be too involved to get in.

**Comment by jipperinbham** [comment]
closed via #393
