### ISSUE TITLE
Enhancement: Add the possibility to require npm packages in transformers

### ISSUE THREAD

**Issue by moooji** [compose/transporter#40]
It seems that it is currently not possible to use <b>require("...")</b> in transformers (transporter does not send any document when require is being used). NPM packages would add a lot of possibilities in the transform step when it comes to parsing and rewriting fields.

**Comment by moooji** [comment]
Ok, I checked the code and discovered that transporter uses the Otto javascript VM (I was assuming that it uses node) - It won't work then I guess :)

**Comment by nstott** [comment]
I think we could probably build some functionality that loads scripts into the vm.  
You're right though, this is js, not node, so there aren't things like file / network access, so I imagine that some modules / parts of modules might not work.  are there specific modules that you'd like to see here?

**Comment by sberryman** [comment]
This would be pretty nice! You talk about on the blog that underscore is automatically available in the transformers but that doesn't appear to be the case (at least in v0.0.3)

**Comment by jipperinbham** [comment]
closing this out as mentioned in previous comments this is a JS VM and npm modules are not something we can do.
