### ISSUE TITLE
Mongodb to ES + resume + oplog size

### ISSUE THREAD

**Issue by mensa23** [compose/transporter#408]
Hi,

I'm migrating the data from mongodb to es with tail, and everything is good! Thanks for the great job.

But about resume reader, my concern is the oplog size. In fact, if the number of data is huge enough, oplog only can store a part of these operations. Does the resume reader work still if we interrupt the transporter process when it's migrating the data which was removed from oplog?

Thanks

**Comment by jipperinbham** [comment]
the resume will work as long as transporter is not down longer than the oplog time window, a general rule of thumb we follow @ compose is to try and have 24 hours of oplog for large deployments
