### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by webfrank** [compose/transporter#417]
## Bug report
During a long running session from mongodb to elasticsearchwith tail option enabled, transporter crashes with this error: context deadline exceeded

### Relevant pipeline.js:
var source = mongodb({
  "uri": "mongodb://localhost:27017/view"
  "timeout": "30s",
  "tail": true,
  // "ssl": false,
  // "cacerts": ["/path/to/cert.pem"],
  // "wc": 1,
  // "fsync": false,
  // "bulk": false,
  //"collection_filters": "{\"events\":{}}",
  // "read_preference": "Primary"
})

var sink = elasticsearch({
  "uri": "http://localhost:9200/events"
  "timeout": "30s", // defaults to 30s
  // "aws_access_key": "ABCDEF", // used for signing requests to AWS Elasticsearch service
  // "aws_access_secret": "ABCDEF" // used for signing requests to AWS Elasticsearch service
})
t.Config({"xlog_dir":"/var/log/transporter"}).Source("source", source, "/^events$/").Save("sink", sink, "/.*/")

### System info:

- Transporter version
VERSION
  0.5.0
- OS
Ubuntu 16.04.3 LTS
- DB version(s)
MongoDB: v3.4.3
ElasticSearch: 5.5.2

### Reproducible Steps:

Start pipeline.js on a collection with over 68M records and wait

### What did you expect to happened?

Continuosly moving from MongoDB to ElasticSearch

### What actually happened?

Crash

**Comment by skyhit** [comment]
I got the same problem

**Comment by jipperinbham** [comment]
this is likely due to wires taking longer than the default timeout of `5s`. You can increase the write timeout in the `Config` function like so:

```javacript
t.Config({'write_timeout': '60s', 'xlog_dir': '/var/log/transporter'})...
```

**Comment by kanukanukanu** [comment]
I got the same problem.
and I modify timeout = 3600s on pipeline.js.
But it couldn't be solved.

you guys have any solution?

**Comment by ahmadsdk** [comment]
I solved this by increasing the write timeout to 3600s, like so:

`t.Config({'write_timeout': '3600s'})`
