### ISSUE TITLE
File adapter + Transformer works but emits unlabeled warning

### ISSUE THREAD

**Issue by codepope** [compose/transporter#43]
Run any Transformer with the File adapter and the process will work but the console will be full of

unknown type: map[string]interface {}
unknown type: map[string]interface {}
unknown type: map[string]interface {}
unknown type: map[string]interface {}
...

Reason is the File adapter emits a map. The map is detected by the Transformer's transformOne function. This then calls mejson.Marshal(msg.Data). Mejson has no code to match with a map[string]interface() so it falls through to default...

	default:
			fmt.Fprintf(os.Stderr, "unknown type: %T\n", v)
			return json.Marshal(v)
		}

which emits the error but still marshals the value allowing the code to work.

Don't know whether to fix in mejson or in the transformer.

**Comment by nstott** [comment]
Hi,
I think this was fixed with an update to mejson, ( https://github.com/compose/mejson/commit/68a977bc080888e17d81320fece9460e285b7ae4 )
Can you please try `go get -u github.com/compose/mejson` and rebuild your transporter?

Thanks!

**Comment by codepope** [comment]
Fixed - wrong mejson was being pulled.
