### ISSUE TITLE
How to use regex expression in collection_filters?

### ISSUE THREAD

**Issue by nbwgl** [compose/transporter#430]
Hi, I'm using trasorter to transfer data from mongodb to elasticsearch.
when I use a regex expression in collection_filters, like this:
"collection_filters": "{\"pois\": {\"adcode\":/^32\d{4}/}}"
there indicate an error in running transporter

E:\SourceCode\amappoi>d:\Tools\transporter.exe run
panic: malformed collection_filters [recovered]
        panic: Panic at 28: malformed collection_filters [recovered]
        panic: Panic at 28: malformed collection_filters

if I change the expression to this:
"collection_filters": "{\"pois\": {\"adcode\":\"/^32\d{4}/\"}}"
It has no record transported to es.
How to do like this?

**Comment by jipperinbham** [comment]
can you provide us with the logs and maybe some sample data?

**Comment by nbwgl** [comment]
still me.
if config like this
"collection_filters": "{\"pois\": {\"adcode\":\"/34\d{4}/\"}}"
it works ,but no rows transported.
if change to 
"collection_filters": "{\"pois\": {\"adcode\":\"/34\\d{4}/\"}}"
or
"collection_filters": "{\"pois\": {\"adcode\":/34\d{4}/}}"
report errors like

panic: malformed collection_filters [recovered]
        panic: Panic at 28: malformed collection_filters [recovered]
        panic: Panic at 28: malformed collection_filters

goroutine 1 [running]:
github.com/compose/transporter/vendor/github.com/dop251/goja.(*Runtime).RunProgram.func1(0xc420143d88)
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/runtime.go:779 +0x98
panic(0x1a0b6c0, 0xc420209100)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm).try.func1(0xc4201a45b0, 0x0, 0xc420143c60, 0x0, 0x0, 0x0, 0xc420143cb8)
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:364 +0x32e
panic(0x1a0b6c0, 0xc420129250)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
main.(*Transporter).Source(0xc4201ef140, 0x21ec360, 0xc4201ef160, 0xc4201dc500, 0x3, 0x4, 0x0, 0x0)
        /Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/goja_builder.go:211 +0x3a9
reflect.callMethod(0xc42020c2a0, 0xc420143a18)
        /usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:640 +0x18a
reflect.methodValueCall(0x21ec360, 0xc4201ef160, 0xc4201dc500, 0x3, 0x4, 0x4, 0x13de8dd, 0xc4201a7750, 0x0, 0x38, ...)
        /usr/local/Cellar/go/1.8.3/libexec/src/reflect/asm_amd64.s:29 +0x40
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc4201a45b0, 0xc4201fcc60, 0x3)
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:1827 +0x2e9
github.com/compose/transporter/vendor/github.com/dop251/goja.call.exec(0xc400000003, 0xc4201a45b0)
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:1808 +0x6ff
github.com/compose/transporter/vendor/github.com/dop251/goja.(*call).exec(0xc4202089f4, 0xc4201a45b0)
        <autogenerated>:816 +0x55
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm).run(0xc4201a45b0)
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:288 +0x7f
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm).(github.com/compose/transporter/vendor/github.com/dop251/goja.run)-fm()
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:375 +0x2a
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm).try(0xc4201a45b0, 0xc420143cc0, 0x0)
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:370 +0x119
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm).runTry(0xc4201a45b0, 0x1b90d68)
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:375 +0x4f
github.com/compose/transporter/vendor/github.com/dop251/goja.(*Runtime).RunProgram(0xc4201aa180, 0xc4201dc480, 0x0, 0x0, 0x0, 0x0)
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/runtime.go:790 +0x210
github.com/compose/transporter/vendor/github.com/dop251/goja.(*Runtime).RunScript(0xc4201aa180, 0x0, 0x0, 0xc4201ec900, 0x435, 0x435, 0x435, 0x435, 0xc4201ec900)
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/runtime.go:769 +0xa8
github.com/compose/transporter/vendor/github.com/dop251/goja.(*Runtime).RunString(0xc4201aa180, 0xc4201ec900, 0x435, 0x635, 0xc4201ec900, 0x435, 0x0)
        /Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/runtime.go:758 +0x51
main.newBuilder(0x7ffeefbffa59, 0xb, 0x1, 0x1, 0x0)
        /Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/goja_builder.go:52 +0x354
main.runTest(0xc4200740e0, 0x1, 0x1, 0x4, 0x0)
        /Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/test.go:20 +0xed
main.main()
        /Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/main.go:63 +0x105

my data like these:

B02270I1E9	新桥服务区	180300	蜀山区	116.894179,31.92057		340104
B0FFGQF5MB	金寨路收费站(G4001合肥绕城高速出口)	180200	蜀山区	117.235426,31.787310		340104
B02270IHEH	肥东服务区	180300	肥东县	117.455542,31.85686		340122
B0FFGUR2JC	蜀山收费站(G4001合肥绕城高速出口)	180200	蜀山区	117.140801,31.853885		340104
B02270IAQD	新桥服务区	180300	蜀山区	116.894277,31.918379		340104

the sixth field is adcode
