### ISSUE TITLE
Tailing three MongoDB’s shard

### ISSUE THREAD

**Issue by alexandrefabre22** [compose/transporter#438]
Hello,

I  use MongoDB shard (mongos), I would like to tail three different shards in the same pipeline. I tested:

"uri":"mongodb://username:password@host1:port1,host2:port2,host2:port2/database?authSource=admin"

but it does not work.

how could I solve it ?

Any advice and suggestions will be greatly appreciated

Thanks!

**Comment by jipperinbham** [comment]
transporter doesn't support tailing from sharded clusters as it's not as straightforward, https://www.mongodb.com/blog/post/pitfalls-and-workarounds-for-tailing-the-oplog-on-a-mongodb-sharded-cluster has some more details. If this is a one time copy, it's likely you'd be able to do it by turning off the balancer while running transporter so there's no worry about chunks being moved around and you'd have to connect a transporter to each individual shard as the oplog isn't exposed through the mongos.
