### ISSUE TITLE
only one type per index in Elasticsearch 6.0

### ISSUE THREAD

**Issue by vioan** [compose/transporter#442]
it seems that the mentioned version of ES is not allowing two types per index. Any solution for that for example when in mongodb we have one database with multiple collections?

https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

Edit: Added the link for doc

**Comment by jipperinbham** [comment]
thanks for the info!

we'll need to make some adjustments to how transporter writes to elasticsearch for better usability. right now, you'd have to create multiple sources and use namespace filtering to send the mongodb database collections to multiple indexes.

**Comment by Olegario96** [comment]
Any news on this issue?

**Comment by mbatchkarov** [comment]
@jipperinbham is it possible to create multiple sources in a single application file, e.g. something like 

``
var source = ...
var sink = ...
t.Source("source", source, "/labels/").Save("sink", sink, "/labels/")
t.Source("source", source, "/documents/").Save("sink", sink, "/documents/")
```

Or should we run multiple `transported` processes, each having a single source and writing to a single index?
