### ISSUE TITLE
transporter is having reading from a sharded monogdb cluster 

### ISSUE THREAD

**Issue by ksugana** [compose/transporter#447]
pipeline looks like this. 

var source = mongodb({
"uri": "mongodb://db-mongod-0:27017,mongod-1:27017,db-mongod-2:27017/dbname?replicaSet=staging-cluster_0",
  "timeout": "300s",
  "tail": true
})

var sink = elasticsearch({
  "uri": "http://localhost:9200/col1"
})

t.Source("source", source, "/^col1$/").Save("sink", sink)

it only reads the collections which are not sharded and it dies after that. 
can anyone let me know if this is even possible ?

**Comment by jipperinbham** [comment]
mongodb does not expose access to replicaset oplogs through the mongos, it's a very complicated problem to try and do for sharded setups due to the way rebalances can occur. all that to say, transporter is not able to easily support sharded mongodb clusters.
