### ISSUE TITLE
Transporter in tail option true, is not able to read the mongodb oplog.rs(option.$main) collection

### ISSUE THREAD

**Issue by narinder-kaur** [compose/transporter#452]
### Relevant pipeline.js:
oplogger is an authorized user having access to the local database.
var source = mongodb({  
  "uri": "mongodb://oplogger:PasswordForOplogger@127.0.0.1:27017/test?authSource=admin",
"tail": true
})
### System info:

- Transporter version : v0.5.2
- OS : Window 7 Enterprise (64 bit OS)
- 
 - Mongodb : 3.6
 - Elasticsearch: 6.1.2

### Reproducible Steps:
1. Started a single mongodb server with --master option in order to get the oplog.rs enabled.
2. Configured the pipleline.js to have the *tail* feature enabled in transporter.
3. Confirmed the access to the local db but it was having a oplog.$main table instead of oplog.rs as its a single server setup under master slave configuration, So there is no slave in the system.

### What did you expect to happened?
When ran the transporter executable, it should have been accessible to the oplog.$main table too and should read and transport the data from there to the Elasticsearch.
### What actually happened?
It was giving the error that oplog.rs collection is not found. There should be either check on both collections or there should be configuration to accept the name of the oplog collection.

**Comment by codepope** [comment]
Hi,

Don't configure for master/slave - that doesn't create the oplog the transporter needs - See https://docs.mongodb.com/manual/reference/local-database/ for why you have oplog.$main. 

Configure Mongodb as a single node in a replica set to get oplog.rs - `--replSet rs0` should do the job. Then the Transporter will be able to see a replica set (rs) oplog (hence `oplog.rs`).

Dj

**Comment by narinder-kaur** [comment]
Thanks for the guidance. Its working as per expected. 

There is one more issue, Deleted documents are not being updated if tail option is not set to true. Tail keeps the service ON, but I do have to run it at some interval. Oplogs are read only in case of tail:true. Is there any other way around to get the deletions updated whenever I run the transporter service next time.

Thanks
Narinder Kaur
