### ISSUE TITLE
"Building Transporter on Windows" need version 1.8 or later for golang

### ISSUE THREAD

**Issue by haijiandong** [compose/transporter#465]
Hi, I read the [document](https://github.com/compose/transporter/blob/master/READMEWINDOWS.md).
> Install Go
First step, download and install Go. Go to https://golang.org/dl/ and install the **go1.4.windows-amd64.msi** file offered.

I thinking that it is a 1.4 version of golang,I got an error:
![tim 20180510123752](https://user-images.githubusercontent.com/12838659/39852742-c76fcc54-5450-11e8-8387-61b0da7814c3.png)

I found that `sort.Slice` was released in the 1.8 version. After install the 1.8 ,I succeeded.
I hope to modify this README,prevent new people like me from making mistakes.
thank you!

**Comment by codepope** [comment]
Fixed in master.
