### ISSUE TITLE
Pipeline only transferring small subset of collection

### ISSUE THREAD

**Issue by gwilakers** [compose/transporter#469]
## Bug report

When trying to use the following pipeline to grab all documents that have not been soft deleted from a single collection, I am seeing the pipeline end early and only transfer 1001 documents. This is consistent no matter when collection in the database I try to transfer from.

A couple notable things that I am not sure if matter when using this tool:

1. I am using CosmosDB (formerly DocumentDB) which is Microsoft's offering for MongoDB databases to transfer over. They even expose and use the Mongo API.
2. The collection(s) I am connected to are sharded.

I am seeing this error as well in the middle of the transfer:

```
INFO[0003] adaptor Stopped                               name=source path=source type=mongodb
INFO[0003] Connections to storage.documents.azure.com:10255 closing (2 live sockets). 
INFO[0003] Socket 0xc4202ccb60 to storage.documents.azure.com:10255: closing: Closed explicitly (abend=false) 
INFO[0003] Socket 0xc4202cdb20 to storage.documents.azure.com:10255: closing: Closed explicitly (abend=false) 
INFO[0003] adaptor Stopping...                           name=sink path="source/sink" type=elasticsearch
```

### Relevant pipeline.js:

```
var source = mongodb({
  uri: 'mongodb://username:password@storage.documents.azure.com:10255/test?replicaSet=globaldb',
  ssl: true,
  timeout: "60s"
  collection_filters: "{\"testcollection\": {\"deleted\": false}}"
})

var sink = elasticsearch({
  uri: 'http://username:password@0.0.0.0:9200/test'
})

t.Source('source', source, '/^testcollection$/').Save('sink', sink, '/^testcollection$/')
```

### System info:

- Transporter version: 0.5.2
- OS: Ubuntu 16.04
- DB version(s)
  Elasticsearch: 6.2.4
  CosmosDB: Uses Mongo 3.4 API (more info here https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-introduction)

### Reproducible Steps:

1. Pretty simple repo steps, just use the pipeline file above.

### What did you expect to happened?

Currently, our collection has some 60,000 docs I would like to transfer over to elasticsearch. 

### What actually happened?

Only 1001 of those docs get transferred.

**Comment by codepope** [comment]
DocumentDB/CosmosDB operates a resource unit scheme for reads and writes. If the requested number of documents is too high, it throttles the request. Most MongoDB drivers do not know how to recover from this throttling; only Microsoft’s own drivers are known to be able to continue the query processing. It’s not a bug in Transporter, more a failing of CosmosDB to communicate their compatibility clearly.

**Comment by gwilakers** [comment]
@codepope Okay, that makes sense that the RUs would play a role here. I will try to tweak those to get the performance that I want for the transfer. Thanks for clearing that up!
