### ISSUE TITLE
mongoDB to Elasticsearch v6.4.0 : context deadline exceeded

### ISSUE THREAD

**Issue by kanukanukanu** [compose/transporter#480]
## Directions

Issues are reserved for actionable bug reports and feature requests.

Before opening an issue, search for similar bug reports or feature requests.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

## Bug report
context deadline exceeded

### Relevant pipeline.js:
var source = mongodb({
  //"uri": "${MONGODB_URI}"
 "uri": 'mongodb://localhost/total_web'
  "timeout": "3600s",
  // "tail": false,
  // "ssl": false,
  // "cacerts": ["/path/to/cert.pem"],
  // "wc": 1,
  // "fsync": false,
  // "bulk": false,
  // "collection_filters": "{}",
  // "read_preference": "Primary"
})

var sink = elasticsearch({
  //"uri": "${ELASTICSEARCH_URI}"
  "uri": 'http://elastic123:123123@~~~~~~~~:9200/total_web'
  "timeout": "1000s", // defaults to 30s
  // "aws_access_key": "ABCDEF", // used for signing requests to AWS Elasticsearch service
  // "aws_access_secret": "ABCDEF" // used for signing requests to AWS Elasticsearch service
  // "parent_id": "elastic_parent" // defaults to "elastic_parent" parent identifier for Elasticsearch
})

t.Source("source", source, "/.*/").Save("sink", sink, "/.*/")

### System info:

- Transporter version
Transporter v0.5.2
- OS
Ubuntu 16.04
- DB version(s)
mongoDB v4.0.3

### Reproducible Steps:

1. ...
2. ...

### What did you expect to happened?
mongoDB to ElasticSearch data transfer

### What actually happened?
"context deadline exceeded" error message appeared.
"timeout reached waiting for out channels to clear path = source"

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by yudao** [comment]
Hi,

@kanukanukanu I've the same error in my elastic cloud.
I've just updated to v6.6.2 and now this error is gone.

**Comment by shubhamvipul** [comment]
Getting the same error for 6.4... any solution to this?
