### ISSUE TITLE
How can I run many transports sequentially?

### ISSUE THREAD

**Issue by kennethlynne** [compose/transporter#484]
### What did you expect to happen?
It should be possible to run many transports sequentially.

### What actually happened?
There is no documentation about how you can figure out that the transport has completed.

## Feature Request
Opening a feature request kicks off a discussion.

### Proposal:
t.Source(..) and t.Save(...) should return a stream or promise so the consumer can figure out when it has completed.

**Comment by theonlyalterego** [comment]
did you ever find a way around this? it seems like it only runs one per pipeline.js file.

I had expected it to run them sequentially.
