### ISSUE TITLE
elastic cloud uri for cloud enterprise 

### ISSUE THREAD

**Issue by sgabbiEWF** [compose/transporter#488]
var sink = elasticsearch({
"uri": "${ELASTICSEARCH_URI}"
// "timeout": "10s", // defaults to 30s
// "aws_access_key": "ABCDEF", // used for signing requests to AWS Elasticsearch service
// "aws_access_secret": "ABCDEF" // used for signing requests to AWS Elasticsearch service
// "parent_id": "elastic_parent" // defaults to "elastic_parent" parent identifier for Elasticsearch
})

I am currently using the elastic cloud enterprise and it doesnt have a single 'uri'.. it has an endpoint where I login with my username and password.. so I am not able to configure it.. do you guys plan to support elastic cloud instances as sink too? What other options do i have?

Cheers,

**Comment by johnjjung** [comment]
@sgabbiEWF 
Believe it or not but you can do something like this:

`<username>:<password>@<https endpoint>:<PORT>`

Example:

`elastic:changeme@https://elasticsearch-host:9200 `

;)
