### ISSUE TITLE
sync mongoDB to es ，lost some data 

### ISSUE THREAD

**Issue by xionggaogao123** [compose/transporter#492]
## Directions

Issues are reserved for actionable bug reports and feature requests.

Before opening an issue, search for similar bug reports or feature requests.
If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
Erase the other section and everything on and above this line.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### System info:

- Transporter version
- OS
- DB version(s)

### Reproducible Steps:

1. ...
2. ...

## Feature Request

Opening a feature request kicks off a discussion.

**Comment by xionggaogao123** [comment]
the mongoDB data have 100000,  and I   sync data to es  with transposter, but the result is lost some data of es

**Comment by fidelio314** [comment]
hi! i have the same issue. i have 24.000.000 entries and the trasporter only indexes to my ES about 1.400.000 entries..
