### ISSUE TITLE
Rejecting mapping update as the final mapping would have more than 1 type

### ISSUE THREAD

**Issue by joaolcorreia** [compose/transporter#495]
## Directions

Using Elastic Search 7.1 (AWS) and DocumentDB Mongo (AWS). 

When using file sink it works great!. When using Elastic I'm getting an error. 

`error="&elastic.ErrorDetails{Type:"illegal_argument_exception", Reason:"Rejecting mapping update to [projectdb] as the final mapping would have more than 1 type: [_doc, finalDB]", ResourceType:"", ResourceId:"", Index:"", Phase:"", Grouped:false, CausedBy:map[string]interface {}(nil), RootCause:[]*elastic.ErrorDetails(nil), FailedShards:[]map[string]interface {}(nil)}" executionID=22 id=5de5c6cee95d554ae04f9e2a index=projectdb type=finalDB version=5 writer=elasticsearch
ERRO[0025] _bulk failed list [933]                       error="&elastic.ErrorDetails{Type:"illegal_argument_exception", Reason:"Rejecting mapping update to [projectdb] as the final mapp`

or it just doesn't do anything. 

`root@fdd:~/pipeline# transporter run projectDB.js 
INFO[0000] boot map[sink:elasticsearch source:mongodb]   ts=1575417352575513765
INFO[0000] starting with metadata map[]                  name=source path=source type=mongodb
INFO[0000] adaptor Listening...                          name=sink path="source/sink" type=elasticsearch
INFO[0000] adaptor Starting...                           name=source path=source type=mongodb
INFO[0000] starting Read func                            db=projectDB
INFO[0000] collection count                              db=projectDB num_collections=2
INFO[0000] skipping iteration...                         collection=capterra db=projectDB
INFO[0000] adding for iteration...                       collection=finalDB db=projectDB
INFO[0000] done iterating collections                    db=projectDB
INFO[0000] iterating...                                  collection=finalDB
INFO[0000] Establishing new connection to docdb-xxxxxxxxxxxxx.us-west-2.docdb.amazonaws.com:27017 (timeout=1h0m0s)... 
INFO[0000] Connection to docdb-xxxxxxxxxxxxx.cluster-cgrhoz7foeif.us-west-2.docdb.amazonaws.com:27017 established. 
INFO[0005] metrics source records: 47540                 path=source ts=1575417357580065682
INFO[0005] metrics source/sink records: 47528            path="source/sink" ts=1575417357580068062
INFO[0005] iterating complete                            collection=finalDB db=projectDB
INFO[0005] Read completed                                db=projectDB
INFO[0005] adaptor Start finished...                     name=source path=source type=mongodb
INFO[0005] adaptor Stopping...                           name=source path=source type=mongodb
INFO[0005] adaptor Stopped                               name=source path=source type=mongodb
INFO[0005] Connections to docdb-xxxxxxxxxxxxx.cluster-cgrhoz7foeif.us-west-2.docdb.amazonaws.com:27017 closing (2 live sockets). 
INFO[0005] Socket 0xc4202cc000 to docdb-xxxxxxxxxxxxx.cluster-cgrhoz7foeif.us-west-2.docdb.amazonaws.com:27017: closing: Closed explicitly (abend=false) 
INFO[0005] Socket 0xc4202ccb60 to docdb-xxxxxxxxxxxxx.cluster-cgrhoz7foeif.us-west-2.docdb.amazonaws.com:27017: closing: Closed explicitly (abend=false) 
INFO[0005] adaptor Stopping...                           name=sink path="source/sink" type=elasticsearch
INFO[0005] received stop, message buffer is empty, closing... 
INFO[0005] adaptor Listen closed...                      name=sink path="source/sink" type=elasticsearch
INFO[0005] adaptor Stopped                               name=sink path="source/sink" type=elasticsearch
INFO[0005] closing BulkProcessor                         version=5 writer=elasticsearch
INFO[0005] metrics source records: 50514                 path=source ts=1575417358046606175
INFO[0005] metrics source/sink records: 50514            path="source/sink" ts=1575417358046609348
INFO[0005] exit map[source:mongodb sink:elasticsearch]   ts=1575417358046610580
root@fdd:~/pipeline# `

Any ideas on how to fix this?

**Comment by dongnguyenvie** [comment]
i have same issue :(

**Comment by mnguyen25** [comment]
The same happens to me

**Comment by mnguyen25** [comment]
@joaolcorreia which version of Elasticsearch you were using? I encountered the same issue with ES 7.10. 
If you have your ES mapping predefined, the `_type` of the index will be `_doc` which will then conflict with what Transporter send to ES. Transporter is sending custom type to ES, in your case, it's `finalDB`. More details [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html). 

To make it works, for now, you might downgrade your ES version to 6. Another workaround is not defining the index in advance -> start the sync process -> stop it immediately as long as the index is created -> delete all docs in the index -> update the mapping of the newly created index -> start the sync process but this time keep it running.
