### ISSUE TITLE
Unable to get in Ubuntu

### ISSUE THREAD

**Issue by Philmod** [compose/transporter#52]
Hey guys,

I simply can't get/build:

```
sudo go get -a ./cmd/...
/usr/lib/go/src/pkg/code.google.com/p/goprotobuf/proto/text.go:39:2: no Go source files in /usr/lib/go/src/pkg/encoding
```

**Comment by codepope** [comment]
Are you building with Go 1.1? That issue can appear because protobuf requires Go 1.2 where the encoding package appears.

I'd recommend downloading and installing the Go 1.4.1 distribution from golang.org and repeating the process.

**Comment by Philmod** [comment]
Ok. You should give more information in the README about the Go's version.

**Comment by nstott** [comment]
Thanks, will do!
