### ISSUE TITLE
Sync data between Mongodb and ElasticSearch errors.

### ISSUE THREAD

**Issue by ngocthanhit** [compose/transporter#56]
Hello all, 
We have an issue when config the sync data from mongodb to ES. 
thanhtruong$ ./transporter eval --config ./test/config.yaml 'Source({name:"localmongo", namespace: "testdb.2b66d7a9-8cb5-4802-838a-f1f58869bbf5_campaigns"}).save({name:"es", namespace: "2b66d7a9-8cb5-4802-838a-f1f58869bbf5_campaigns.testdata"})'
Mongo Config {URI:mongodb://localhost/testdb Namespace:testdb.2b66d7a9-8cb5-4802-838a-f1f58869bbf5_campaigns Debug:true Tail:false Wc:0 FSync:false Bulk:false}
setting start timestamp: 6111893325843791872
transporter: CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [4])
transporter: CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [4])
transporter: CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [3])
transporter: CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [4])
transporter: CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [4])

Did someone see it before? Here are the nodes of my transporter: 
thanhtruong$ ./transporter list --config ./test/config.yaml
Name                 Type            URI
localmongo           mongo           mongodb://localhost/tokyo_api_development_campaigns
es                   elasticsearch   http://127.0.0.1:9200/2b66d7a9-8cb5-4802-838a-f1f58869bbf5_campaigns

Thanks for your help.

**Comment by codepope** [comment]
You may be hitting an Elasticsearch mapping issue, assuming that you are letting ES auto-type your data. Have a look at this article - https://blog.compose.io/transporter-and-elasticsearch-mapping/ - where I explain the problem and a way to work around it.

**Comment by ngocthanhit** [comment]
Thanks @codepope . My mapping was too complex. I will try a simple mapping first. 
Thanks again. 

Thanh.

**Comment by ngocthanhit** [comment]
Hello @codepope,
Can you help to review my ES index? Basically I used all the string data-type but it still fired the same problem: 
My ES index is : 

 curl -XPUT 'http://127.0.0.1:9200/foos/foo/_mapping' -d '
{
    "foo": {
        "properties": {
            "projectName": {"type": "string"},
            "logType": {"type": "string"},
            "logSource": {"type": "string"},
            "logTime": {"type": "string"},
            "host": {"type": "string"},
            "body": {"type": "string"}
        }
    }
}'

And after run the transporter, it saw the same problem bofore: 
./transporter eval --config ./test/config.yaml 'Source({name:"localmongo", namespace: "tokyo_api_development_campaigns.foo"}).transform({name: "mappingtrans", filename: "test/transformers/mapping.js", debug: true}).save({name:"es", namespace: "foos.foo", debug: true})'

Mongo Config {URI:mongodb://localhost/tokyo_api_development_campaigns Namespace:tokyo_api_development_campaigns.foo Debug:true Tail:false Wc:0 FSync:false Bulk:false}
setting start timestamp: 6111933101535920128
transporter: CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [1])

I also check the data in ES and just the _id from mongodb synced to the ES.

Thanks 

Thanh.

**Comment by ngocthanhit** [comment]
Hi @codepope 
I can solve above issue, but i have a question which want to ask you : 
How can i make the transporter to run as a process , right now after run the transporter command, it was quite after that. Here is the logs : 
thanhtruong$ ./transporter run --config ./test/config.yaml ./test/aaa.js
Mongo Config {URI:mongodb://localhost/testdb Namespace:testdb.foo Debug:true Tail:false Wc:0 FSync:false Bulk:false}
setting start timestamp: 6112294905285967872 

Thanks.

**Comment by lvidarte** [comment]
@codepope can you explain how to solved the issue?
