### ISSUE TITLE
How can i make the transporter to run as service/daemon ? 

### ISSUE THREAD

**Issue by ngocthanhit** [compose/transporter#57]
How can i make the transporter to run as a background/daemon mode?  right now after run the transporter command, it was quite after that. Here is the logs : 
thanhtruong$ ./transporter run --config ./test/config.yaml ./test/aaa.js
Mongo Config {URI:mongodb://localhost/testdb Namespace:testdb.foo Debug:true Tail:false Wc:0 FSync:false Bulk:false}
setting start timestamp: 6112294905285967872
thanhtruong$ 

Thanks

**Comment by codepope** [comment]
If you want it to continue synchronising the updates from the database, set tail to true. This will initiate oplog tailing of the source MongoDB.

**Comment by ngocthanhit** [comment]
Thanks. i can run the continue synchronishing now.

**Comment by nguyentungson** [comment]
@codepope : Hi...
"If you want it to continue synchronising the updates from the database, set tail to true. This will initiate oplog tailing of the source MongoDB."... How to set tail to true. Thanks

**Comment by shividhar** [comment]
@codepope You'll have to set tail: true in the config.yaml
