### ISSUE TITLE
facing issue while fetching dependencies

### ISSUE THREAD

**Issue by mandeepm91** [compose/transporter#58]
I was trying to install transporter on ubuntu 14.04. Earlier it used to work fine. I'm trying on a new machine and after executing the command:

```
go get -a ./cmd/...
```

I am getting the error:

```
go install: no install location for directory /home/mandeep/go/transporter/cmd/transporter outside GOPATH
```

**Comment by ngocthanhit** [comment]
Hi, 

I think you need to set the $GOPATH var correctly to your GO project folder and it will work. In your case, set GOPATH to /home/mandeep/go
and create those sub-folders : 
bin	pkg	src

**Comment by nstott** [comment]
That's right, 
The way the GOPATH is organized is explained in the top of this document http://golang.org/doc/code.html

**Comment by mandeepm91** [comment]
thanks! the issue was with GOPATH only.
