### ISSUE TITLE
tar.gz releases seems to be compressed twice

### ISSUE THREAD

**Issue by fredoche** [compose/transporter#59]
Hi,
I wanted to bring to your attention that your release files are compressed twice, which unnecessarily complicates decompression using a single tar command.
```
$ file transporter_linux_amd64.tar.gz
-> transporter_linux_amd64.tar.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT)
$ gunzip transporter_linux_amd64.tar.gz && file transporter_linux_amd64.tar
-> transporter_linux_amd64.tar: gzip compressed data
```
Sorry to slice hairs for such little details.

**Comment by nstott** [comment]
Thanks for the heads up
We're using goxc to bundle the releases
(see https://github.com/compose/transporter/blob/master/circle.yml#L27 )
I'll have a look and see if this is an issue with them, or with the way we're calling this
Thanks

**Comment by nstott** [comment]
Catching up on old issues, 
This doesn't seem to be a problem with the latest build, 
are you seeing the same things on https://github.com/compose/transporter/releases/tag/v0.0.4 ?

Thanks

```
ubuntu@box497:/tmp/circle-artifacts.djul7Hl/transporter-xc/snapshot$ file transporter_linux_amd64.tar.gz
transporter_linux_amd64.tar.gz: gzip compressed data
ubuntu@box497:/tmp/circle-artifacts.djul7Hl/transporter-xc/snapshot$ gunzip transporter_linux_amd64.tar.gz
ubuntu@box497:/tmp/circle-artifacts.djul7Hl/transporter-xc/snapshot$ file transporter_linux_amd64.tar
transporter_linux_amd64.tar: POSIX tar archive
```

**Comment by fredoche** [comment]
Tried with GNU tar -xvzf, it now uncompress fine. Thanks.

**Comment by nstott** [comment]
awesome, thanks for checking
