### ISSUE TITLE
Version support for elasticsearch, mongodb and others

### ISSUE THREAD

**Issue by fredoche** [compose/transporter#61]
Having trouble to set up a simple transport between mongodb and elasticsearch, I was wondering if my problems could come from the versions I use. Which version do you recommend to work with transporter?

Thanks

**Comment by fredoche** [comment]
More specifically, I use es version 1.3 and get the following output when starting the transport:

[2015-02-17 17:40:01,931][WARN ][http.netty               ] [Spellbinder] Caught exception while handling client http traffic, closing connection [id: 0x6b2d9367, /127.0.0.1:48156 => /127.0.0.1:9200]
java.lang.IllegalArgumentException: invalid version format: ￀￀

**Comment by codepope** [comment]
Could you give us a snapshot of your config.yaml and application.js ?

**Comment by fredoche** [comment]
api:
   interval: 1s
#   uri: "http://requestb.in/13gerls1"
#   key: "48593282-b38d-4bf5-af58-f7327271e73d"
#   pid: "something-static"
nodes:
  localmongo:
    type: mongo
    uri: mongodb://localhost:27017/coorpacademy
    namespace: coorpacademy.users
    debug: true
  es:
    type: elasticsearch
    namespace: coorpacademy.users
    uri: https://localhost:9200/digital
    debug: true
  foofile:
    type: file
    uri: file:///tmp/foo
  stdout:
    type: file
    uri: stdout://

**Comment by fredoche** [comment]
Hi, here's the following 
'''
api:
   interval: 1s
#   uri: "http://requestb.in/13gerls1"
#   key: "48593282-b38d-4bf5-af58-f7327271e73d"
#   pid: "something-static"
nodes:
  localmongo:
    type: mongo
    uri: mongodb://localhost:27017/coorpacademy
    namespace: coorpacademy.users
    debug: true
  es:
    type: elasticsearch
    namespace: coorpacademy.users
    uri: https://localhost:9200/digital
    debug: true
  foofile:
    type: file
    uri: file:///tmp/foo
  stdout:
    type: file
    uri: stdout://
'''

**Comment by codepope** [comment]
Just a quick thing to check, can you change the uri for Elasticsearch to http://localhost:9200/ as by default that's not a HTTPS port.

**Comment by fredoche** [comment]
Ok that was it, thanks... Once again bitten by copypasting. 
I'm still having and issue though: 
```
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [_id]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:414)
```
but it is unrelated, I'll look into this now but if you have a clue about the next step, I'll take it :)
Thanks a lot.

**Comment by fredoche** [comment]
seems related to #60
