### ISSUE TITLE
Transporter does not remove deleted document from index

### ISSUE THREAD

**Issue by fredoche** [compose/transporter#62]
Hi,
I have an issue here, where transporter does not remove deleted documents from index.
Since transporter replaces rivers, I expected such functionality. Is it out of scope of transporter or am I doing something wrong?
Thanks for help

**Comment by Winslett** [comment]
I've had similar behavior with Mongo -> Mongo copies.  Deleted documents in MongoDB are basically `_id` only documents, i.e. `{_id: ObjectId("<id>")}`.

What is your source database type?

**Comment by fredoche** [comment]
mongo -> elasticsearch . I worked around this issue using a typical  elasticsearch pattern, which is a rotating index. I build a new ES index every N minutes, and atomically update an alias after a transporter run.

**Comment by shividhar** [comment]
+1 Same issue

**Comment by nstott** [comment]
There are a number of issues right now surrounding this functionality in transporter
on inserts and updates the document is run through the transformer which can potentially update the _id for insertion into other databases, however for deletes the document is passed through without transformation.  this behaviour needs to change

**Comment by nstott** [comment]
We've made a change in the recent transporter build, 
transformers now have full access to the transporter message, not just the document.
have a  look at the changelog for the format of the msg, (we'll be writing a blog post soon about this)
https://github.com/compose/transporter/blob/master/CHANGELOG.md

deletes are now processed by transformers, so if your _id changes between databases and there is logic that needs to happen, that can be done in the transformer directly

**Comment by Alino** [comment]
+1 for the blogpost :D

**Comment by jipperinbham** [comment]
@fredoche we believe this has been resolved with the 0.0.4 release. You can checkout a blogpost on the changes [here](https://www.compose.io/articles/transporter-0-0-4-more-control/)

**Comment by Alino** [comment]
I am tailing mongo oplog and moving the data with transporter into elastic search.
So what exactly needs to be done so the documents will be automatically deleted from ES?

**Comment by Alino** [comment]
I don't know if there is actually some solution to remove data from transporter as soon as it's removed from mongo. Please could someone say if it's being worked on or if it's some hidden feature?

**Comment by iammichiel** [comment]
We are having the same issue. As there is no other solution for the moment, we are going to setup two different jobs for the moment. 
- A first one, running frequently updating data all day long.
- A second one, running once a day, deleting all data from destination and re-inserting everything. 

However, I consider this as a temporary workaround. If no solution is found, we will definitely find abandon transporter. **Having a day long of potential out of data is a no-go**.

**Comment by Alino** [comment]
@iammichiel if you abandon transporter please let us know what other solution did you go for.
I know that rivers are deprecated. Or I could tail mongo oplog by myself in my app...

**Comment by Alino** [comment]
So I abandoned transporter completely, and I created my own solution to sync MongoDB with ElasticSearch written in javascript using meteor.js framework, if anyone is interested I could make it open source. My solution also supports custom transformations, and AUTOMATICALLY DELETES removed mongodb documents from ElasticSearch...
I call it Mongo2ES.

**Comment by gdw2** [comment]
@Alino , please share.

**Comment by chiefy** [comment]
@Alino :+1: was thinking similar since this project seems kind of abandoned?

**Comment by jipperinbham** [comment]
@Alino @gdw2 @chiefly we apologize for not addressing this and other issues lately. We've been working to figure out how to best manage this project and will possibly (read: hopefully) be hiring someone to specifically run and manage the project full time soon. If you happen to know of someone, please send them my way.

**Comment by Alino** [comment]
@gdw2 https://github.com/Alino/Mongo2ES

**Comment by SukhikhN** [comment]
Transorter v0.1.1 successfully syncs remove operations for me. Not yet in production, but for simple one collection replication from MongoDB to ElasticSearch it works.

**Comment by jipperinbham** [comment]
closing this in favor of https://github.com/compose/transporter/issues/209
