### ISSUE TITLE
Change _bulk api endpoint to  /{index}/_bulk

### ISSUE THREAD

**Issue by fredoche** [compose/transporter#66]
Hi,
I am currently investigating the possibility of adding ACL to my ES instance. I'm doing that by using a reverse proxy and filter http request based on urls. It seems that transporter access directly the /_bulk endpoint. This api allows edition and deletion of any documents for any index.
Do you think it is possible that transporter uses instead a variation, the /{index}/_bulk endpoint?

**Comment by nstott** [comment]
yeah, that's something that should be pretty easy to get in, I'll see if I can push that in this weekend
would this be something that should be configurable, or a default change
