### ISSUE TITLE
Installation failing at go get -a ./cmd/...

### ISSUE THREAD

**Issue by mandeepm91** [compose/transporter#67]
I am getting the following error when I execute the command:

~~~
go get -a ./cmd/...
~~~

Error:
~~~
go build github.com/compose/transporter/cmd/transporter: signal: killed
~~~

**Comment by mandeepm91** [comment]
retried today. Worked fine now

**Comment by nstott** [comment]
Great, that looks like something on your system was killing the go process, perhaps an oom?
closing this for now, please re-open it if you have similar troubles
