### ISSUE TITLE
Error while using tail

### ISSUE THREAD

**Issue by lcalvy** [compose/transporter#69]
Hi,

After a lot of tests, I can't find a way to use tail option between mongodb and elasticsearch.

I have created same user on user database and system local database, also tried on admin database
With this user I can log and query local["oplog.rs"] collection using mongodb shell but transporter return error 

```bash
CRITICAL: Mongodb error (error reading collection not authorized for query on local.oplog.rs)
```

I tried several uri format, my understanding is that this pattern should work
mongodb://<oploguser>:<oplogpwd>@xxxxxx.mongolab.com:12345/local?authSource=db-stats

Could you see if this is an issue or a misconfiguration from my side.
Regards

* MongoDB is version 2.4.10 hosted on mogolab
* Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-* 2782.20.48~5/RELEASE_X86_64
transporter 0.0.3

**Comment by codepope** [comment]
Are you using a user that has access to the oplog? If not, see the instructions at  http://docs.mongolab.com/oplog/ to create the appropriate user. If you are on a free tier there, you don't have oplog access I believe.

**Comment by lcalvy** [comment]
Yes as mentioned before I can use this user to connect to oplog with mongoshell.
I finnally find a way to connect oplog user with a url pattern like that;
mongodb://oploguser:oplogpwd@xxxxxx.mongolab.com:12345/db-stats

But now I found another issue when passing several source namespaces to transporter. All namespaces are configured to tail:true. Tailing oplog is OK but only on first namespace and output stay on first namespace debug message
```bash
setting start timestamp: 6137631385516507136
```
Is there any parallelism for all namespaces while tailing?

**Comment by Alino** [comment]
can someone confirm this please? That it is currently not possible to tail multiple mongodb collections so they would be all synced inside ElasticSearch?

**Comment by jipperinbham** [comment]
hi @Alino, we're currently working on that in https://github.com/compose/transporter/pull/101. As you can see in the PR, it will be possible to do what you are needing very soon. The only limitation that could affect you is that it's limited to a single database.

**Comment by Alino** [comment]
hi @jipperinbham that's good to hear, thank you. I will be happy to use this then for my data replication.

**Comment by jipperinbham** [comment]
best I can tell, this issue was fixed via https://github.com/compose/transporter/pull/101
