### ISSUE TITLE
Intermittent Elasticsearch bulk insertion errors

### ISSUE THREAD

**Issue by shardnit** [compose/transporter#70]
Hi,

We are disgruntled users of Elasticsearch-Mongo river and eager to replace it with transporter on production. While running transporter on our staging environment, we often see it throwing Elasticsearch bulk insertion errors. 
- `transporter: CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [33])`

Does Transporter retries to insert failed documents? If not, whats the recommended way to catch these documents in file or something, so that we can insert these document into Elasticsearch through another service (or potentially through Transporter again).

**Comment by mmeeoorroo** [comment]
+1 I have the same problem too

**Comment by nstott** [comment]
interesting,
There isn't a retry on this right now, it's tricky to do a retry with the bulk inserts, we need to be able to find which documents specifically failed.
We have the same problem with mongo, but with mongo we are able to retry before failing.
I'll see if i can get that functionality into the elasticsearch driver as well, or at least dump out which documents failed, and why

**Comment by mattmarcello** [comment]
Any updates on this?  I am having the same issue.

**Comment by shividhar** [comment]
+1 Same Error.

**Comment by shividhar** [comment]
Please reference #78. The inherent cause of the error is ElasticSearch isn't able to import one of the MongoDB documents. This could be because your transformer doesn't allow certain documents to be transported or due to a mapping issue.

**Comment by Alino** [comment]
+1 same error now :(

**Comment by adeshpandey** [comment]
+1 same error for me.
none of the issues #78, #81 #73 helped me.
I am facing same issue even inside transformer **_id** is not accessible directly from **doc**.  **doc** has **data** key which contains ** _id**.

**Comment by henriquesa** [comment]
@adeshpandey https://www.compose.io/articles/transporter-0-0-4-more-control/ the message format was changed and now the document data is inside the data object.

This issue on my end was relying on ES' automatic data mapping and then throwing another type on it after a few million objects. Using the transformer to standardize the data types worked out great.

**Comment by ssunzulily** [comment]
In the error message, transporter should hint user to check elastic search logs.

**Comment by jipperinbham** [comment]
closing this in favor of https://github.com/compose/transporter/issues/209
