### ISSUE TITLE
Transporter as demon listening to OpLog 

### ISSUE THREAD

**Issue by pavanputhra** [compose/transporter#71]
How can I run transporter as demon, such that it will always be listening to OpLog and update elastic-search accordingly?

**Comment by shividhar** [comment]
+1

**Comment by nstott** [comment]
I think the easiest way would be to use something like supervisor or write init scripts (linux) to handle this.
I think there are enough tools out there that can handle daemonizing services to make this a little out of scope for transporter itself.

Hopefully someone finds a way to run transporter as a service :)
