### ISSUE TITLE
How can i make the transporter to run as service/daemon ?

### ISSUE THREAD

**Issue by nguyentungson** [compose/transporter#74]
Here is the logs : 
[tungns@server3 transporter]$ transporter run --config ./test/config.yaml ./test/application.js
Mongo Config {URI:mongodb://xxx:xxxx@xxxxxx.mongolab.com:xxxx/nameDB nameDB.bar Debug:true Tail:false Wc:0 FSync:false Bulk:false}
setting start timestamp: 6157120426687332352

But when I checked it does not sync!
Pls help me!
Thanks all!!

**Comment by shividhar** [comment]
Hi. I encountered this issue with MongoLab as well. Except in my instance it syncs once before terminating. This means that the oplog tailing is not working. I also get the following error `transporter: CRITICAL: Mongodb error (error reading collection not authorized for query on local.oplog.rs)`. I would appreciate if you could tell me how you got it to work on MongoLab.
