### ISSUE TITLE
When adding data in mongodb but looking in the elastic is not seen unless running back run command ...

### ISSUE THREAD

**Issue by nguyentungson** [compose/transporter#75]
I have connected the elasticsearch and mongodb. But when I add the data in mongodb .then I search in elatissearch, then no data. What do I do?

**Comment by codepope** [comment]
You'll need to give us the configuration files and JavaScript files you are using to run the Transporter before we can work out what's going on.

**Comment by nguyentungson** [comment]
yep! Here log :
config.yaml
nodes:
  localmongo:
    type: mongo
    uri: mongodb://shoponline:xxxx@xxxx.xxx.com:27017/shoponline
    namespace: shoponline.foo
    debug: true
  es:
    type: elasticsearch
    uri: http://server3.oohhay.com:9200/
--------------
Source({name:"localmongo", namespace:"shoponline.demo", tail: true, bulk: true})
.transform({filename: "transformers/addFullName.js"})
.save({name:"es", namespace:"demo.demo"});

pls help me!!!

**Comment by codepope** [comment]
Your configuration file is not set up to copy later changes. It will copy the data in the MongoDB and then exit. If you want it to copy changes in MongoDB after that initial copy, you need to add tail: true to the localmongo node definition.

**Comment by nguyentungson** [comment]
Thanks! I will try your way...

**Comment by nguyentungson** [comment]
@codepope : It worked, thanks a lot!

**Comment by nguyentungson** [comment]
@codepope  : When I save the data then sync it was mongo side data in but when I delete a elasticsearch data, the raw data still elasticsearch data. Can you help me!

**Comment by nstott** [comment]
Great, thanks!  I'm closing this for now
