### ISSUE TITLE
adaptor for mysql

### ISSUE THREAD

**Issue by kerwin** [compose/transporter#76]
need adaptor for mysql.

**Comment by nstott** [comment]
A Mysql adaptor would be great, 
I'd like to stabalize some of the internal mechanisms before adding new adaptors, 
but if you feel like taking this on yourself, then that would be great.  
Is there a way within mysql that you can query the binlog

**Comment by tuler** [comment]
+1

**Comment by yupengfei** [comment]
Is this function in development?

**Comment by jipperinbham** [comment]
@yupengfei not at the moment as I'll need to spend some time reading up on the MySQL binlog internals. 

would love some help on it though

**Comment by yupengfei** [comment]
@jipperinbham Sorry to reply late, I know nothing about binlog, but this may help https://github.com/siddontang/go-mysql

**Comment by jipperinbham** [comment]
nice! I had not come across that package before but looks to be something we can use.

**Comment by countstarlight** [comment]
@jipperinbham Thank you for your work, is there any progress now?
