### ISSUE TITLE
Mongodb -> Elasticsearch: repeated error "mejson: unknown type: uint8"

### ISSUE THREAD

**Issue by letsgolesco** [compose/transporter#77]
I'm using the transporter to move data from a mongodb instance to elasticsearch. I'm using a transformer to pick certain fields as per your examples.

When I run the transporter, this error is repeated like crazy: `mejson: unknown type: uint8`

It doesn't kill the transporter (data still makes it through), but it's pretty annoying and makes me worried that some data isn't going to make it through the pipe.

Any idea what's going on here?

**Comment by letsgolesco** [comment]
An update for this:

I have three collections I'm transporting. Two of them cause this error to flood, one of them does not (no idea why, trying to figure out the key differentiator).

One of the collections that triggers this error has only 152 documents, but causes the error to appear 1176279 times (I logged stdout & stderr to a file to see).

The data is copied over just fine, but this is pretty annoying for the other collection which has 20,000+ documents...

**Comment by nstott** [comment]
Thanks, that's annoying
this has to do with the type marshalling in the mejson library we're using, it needs to be updated to include the uint8 type

**Comment by letsgolesco** [comment]
Thanks for the reply. Not sure how much of a priority this is for you guys - think it's something I could handle on my own fairly easily in the meantime?

Also, out of curiosity, do you have any idea why some mongodb collections would contain uint8 type and some wouldn't? Any specific type of field that would use it?

**Comment by codepope** [comment]
Uint8 would probably be only generated by something like a sequence or values under 255, byte values.

**Comment by letsgolesco** [comment]
Thanks for the reply @codepope 

Do you think it'd be safe to add `uint8` as a case here to get around this issue? https://github.com/compose/mejson/blob/master/marshal.go#L45

**Comment by codepope** [comment]
Yes. It'll suppress the error but return the same value.

**Comment by nstott** [comment]
fixed with https://github.com/compose/mejson/commit/a53014fefceabf69c0fe2d3219d5d39ea9fbe9da
thanks!

I've seen this happen before on inserts with different drivers, eg the mongo cli will insert numbers with one type, and the go driver will use another

**Comment by letsgolesco** [comment]
Thanks for the timely response & quick fix guys!
