### ISSUE TITLE
gorethink package blocking build from source

### ISSUE THREAD

**Issue by kylemclaren** [compose/transporter#79]
FYI @nstott @jipperinbham:

```sh
➜  transporter git:(master) go get -a ./cmd/...
# gopkg.in/dancannon/gorethink.v0
../../../gopkg.in/dancannon/gorethink.v0/connection.go:22: undefined: ql2.Response_ResponseNote
```

**Comment by nstott** [comment]
Thanks @kylemclaren , try 
`go get -u ./...`
or, `go get -u gopkg.in/dancannon/gorethink.v1`
-u updates the dependencies of the named packages as well as the packages themselves
