### ISSUE TITLE
Support for environment variables in config

### ISSUE THREAD

**Issue by letsgolesco** [compose/transporter#88]
I've been attempting to run a setup locally involving mongodb, elasticsearch and transporter all on docker.

The dockerization works for all 3, but in order for them to communicate via docker links (which are preferred over exposed ports) the config must have access to environment variables, as docker link addresses/ports are defined in env variables.

This isn't just an issue with docker - anyone using a PaaS that exposes config info via env variables (e.g. heroku) may hit issues here.

Support for environment variables in the config.yaml or via command line args would be greatly appreciated!

**Comment by nstott** [comment]
:+1:  good idea, I'll get this onto the road map
