### ISSUE TITLE
Custom Adapters are difficult to create deploy/maintain

### ISSUE THREAD

**Issue by codepope** [compose/transporter#89]
If a user makes a custom adaptor for Transporter, that adaptor requires edits to the registry file. For this to be maintainable would require a fork. It could be suggested that rather than a custom adapter, the user develop a command using the library components that are available. It seems, though, that this means losing out on the flexibility of being able to create pipelines in JavaScript unless you roll your own pipeline generator. 

So a user is left with two unenviable choices if they want an adapter and the flexibility of Transporter configuration

A) fork the Transporter and maintain it with a custom adaptor in place 
B) build a command which uses the Transporter libraries and either forego or reimplement the configurable pipeline.

If it were possible to build and install standalone adaptors which were run and managed by the transporter and used some form of IPC/Messaging to communicate with the Transporter pipeline, it would seem to be a more flexible solution.

**Comment by nstott** [comment]
Thanks for the suggestion, 

It would be great if we could link new adaptor modules into the pipeline without recompiling
it will also be good once we are able to self host transporter adaptors in other languages, which is on the (far out) road map.

for now, I think it's a good enough solution to use transporter as a library for custom adaptors
