### ISSUE TITLE
Error: CRITICAL: Mongodb error (error reading collection read tcp 127.0.0.1:3001: i/o timeout)

### ISSUE THREAD

**Issue by shividhar** [compose/transporter#99]
I get the error: "CRITICAL: Mongodb error (error reading collection read tcp 127.0.0.1:3001: i/o timeout)" which shuts down the transporter script. I set the tail to true because I need to have it persistently running.

**Comment by jipperinbham** [comment]
When you were testing this locally, did you have 2 things in place:

1. the user connecting to the database had permissions to read from the `oplog.rs` collection in the `local` database
2. you were running the database as a replica set; by default MongoDB will not run as a replica set, you have to specify `--replSet rs0` when staring up the `mongod` process

**Comment by shividhar** [comment]
I don't know if the user has permissions to read from the `oplog.rs` collection and I don't know how to set it up. The mongo instance has a replica set when I started the process.

**Comment by shividhar** [comment]
Problem only occurs when I put my computer to sleep when I'm testing locally. Otherwise I don't encounter this issue.
